- src/NATS.Client.Core/INatsSerializer.cs
- src/NATS.Client.Core/InboxSubscriber.cs
- src/NATS.Client.Core/Internal/NatsReadProtocolProcessor.cs
- src/NATS.Client.Core/NatsConnection.LowLevelApi.cs
- src/NATS.Client.Core/NatsConnection.Ping.cs
- src/NATS.Client.Core/NatsConnection.Publish.cs
- src/NATS.Client.Core/NatsConnection.Util.cs
- src/NATS.Client.Core/NatsConnection.cs
- src/NATS.Client.Core/NatsMsg.cs
- src/NATS.Client.Core/NatsOptions.cs
- src/NATS.Client.Core/NatsReplyHandle.cs
- src/NATS.Client.Core/NatsSub.cs
- tests/NATS.Client.Core.Tests/NatsConnectionTest.Auth.cs
- tests/NATS.Client.Core.Tests/NatsConnectionTest.cs
- tests/NATS.Client.Core.Tests/RequestReplyTest.cs
- tests/NATS.Client.Core.Tests/SubscriptionTest.cs
- tests/NATS.Client.Core.Tests/_Utils.cs
Inbox subscriber implementation with minimized allocations for requests.
> Inbox subscriber implementation

- .github/workflows/release.yml
Release workflow to run on merge.
> First alpha release

- .github/workflows/test.yml
- sandbox/NatsBenchmark/Program.cs
- src/NATS.Client.Core/Internal/InboxSub.cs
- src/NATS.Client.Core/Internal/SubscriptionManager.cs
- src/NATS.Client.Core/NatsConnection.cs
- src/NATS.Client.Core/NatsSub.cs
- tests/NATS.Client.Core.Tests/SubscriptionTest.cs
- tests/NATS.Client.Core.Tests/_Utils.cs
Changed GitHub workflow to test against both dev and main versions of `nats-server`.
Sorry for the noise. Main change is in `.github/workflows/test.yml`.
> Test matrix for NATS Server versions

- src/NATS.Client.Core/Commands/CommandBase.cs
- src/NATS.Client.Core/Commands/PublishCommand.cs
- src/NATS.Client.Core/INatsConnection.cs
- src/NATS.Client.Core/Internal/SubscriptionManager.cs
- src/NATS.Client.Core/Internal/TcpConnection.cs
- src/NATS.Client.Core/NatsConnection.LowLevelApi.cs
- src/NATS.Client.Core/NatsConnection.Ping.cs
- src/NATS.Client.Core/NatsConnection.Publish.cs
- src/NATS.Client.Core/NatsConnection.cs
- src/NATS.Client.Core/NatsMsg.cs
- src/NATS.Client.Core/NatsOptions.cs
- src/NATS.Client.Core/NatsPubOpts.cs
- tests/NATS.Client.Core.Tests/CancellationTest.cs
- tests/NATS.Client.Perf/Program.cs
* Publish no-wait option
* Publish command without value task attached
* Default command channel is bounded to 1,000
* Ping is made to wait on the channel if full
> No-wait publish command

- tests/NATS.Client.Core.Tests/NatsConnectionTest.Auth.cs
Added subscription synchronization to avoid intermittent test failures. Actual failure was at the end of the test method where it was testing the re-connect, but to be consistent put same method of synchronization to the previous pub/sub assert as well.
Recent test reconnect failures due to subscription synchronization were exacerbated because of the change to the way subscriptions are restored on reconnect.
> Connect auth test subscriber sync fix

- src/NATS.Client.Core/Internal/SubscriptionManager.cs
- tests/NATS.Client.Core.Tests/RequestReplyTest.cs
Internal inbox subscription options was being used to create the real mux-inbox subscription (on first subscription attempt), which I noticed when trying to use timeouts with request-reply calls. Timeout was ending the real mux-inbox which was causing the rest of the request-reply calls to silently fail.
> Inbox subscription options fix

- src/NATS.Client.Core/Internal/NatsPipeliningWriteProtocolProcessor.cs
- src/NATS.Client.JetStream/NatsJSContext.cs
- src/NATS.Client.JetStream/NatsJSException.cs
- src/NATS.Client.JetStream/NatsJSLogEvents.cs
- src/NATS.Client.JetStream/NatsJSOpts.cs
- src/NATS.Client.ObjectStore/NatsObjStore.cs
- tests/NATS.Client.CheckNativeAot/Program.cs
- tests/NATS.Client.JetStream.Tests/ConsumerConsumeTest.cs
- tests/NATS.Client.JetStream.Tests/ConsumerFetchTest.cs
- tests/NATS.Client.JetStream.Tests/ConsumerNextTest.cs
- tests/NATS.Client.JetStream.Tests/JetStreamTest.cs
- tests/NATS.Client.JetStream.Tests/PublishTest.cs
* Fixes JS publish no reply issue e.g. when connection drops between request and waiting for reply
resolves #29
> JetStream publish options

- tests/NATS.Client.CheckNativeAot/Program.cs
- tests/NATS.Client.Services.Tests/ServicesTests.cs
- tests/NATS.Client.TestUtilities/Utils.cs
Issue with FindServices() call was also happening in native AOT checks.
> Services tests fix an tidy-up

- src/NATS.Client.Services/INatsSvcContext.cs
- src/NATS.Client.Services/INatsSvcServer.cs
- src/NATS.Client.Services/NatsSvcContext.cs
- src/NATS.Client.Services/NatsSvcServer.cs
- tests/NATS.Client.Core.MemoryTests/NatsSubTests.cs
Defined Services public interfaces to indicate what is supported and help with dependency injection and unit testing scenarios.
contributes to #105
> Services interfaces

- tests/NATS.Client.TestUtilities/NatsServer.cs
Version check is available now server with TLS first is released.
> Test TLS first check update

- src/NATS.Client.JetStream/NatsJSOrderedConsumer.cs
- src/NATS.Client.Services/INatsSvcContext.cs
- tests/NATS.Client.Core.MemoryTests/NatsConsumeTests.cs
- tests/NATS.Client.JetStream.Tests/ClusterTests.cs
- tests/NATS.Client.TestUtilities/NatsServer.cs
Done as separate PR to not clutter others.
> Fixed warnings and format

- docs/documentation/core/pub-sub.md
- src/NATS.Client.Core/INatsConnection.cs
- src/NATS.Client.Core/INatsSub.cs
- src/NATS.Client.Core/NatsConnection.Subscribe.cs
- src/NATS.Client.Core/NatsSubUtils.cs
- tests/NATS.Client.CheckNativeAot/Program.cs
- tests/NATS.Client.Core.MemoryTests/NatsSubTests.cs
- tests/NATS.Client.Core.Tests/CancellationTest.cs
- tests/NATS.Client.Core.Tests/JsonSerializerTests.cs
- tests/NATS.Client.Core.Tests/NatsConnectionTest.Auth.cs
- tests/NATS.Client.Core.Tests/NatsConnectionTest.Headers.cs
- tests/NATS.Client.Core.Tests/NatsConnectionTest.QueueGroups.cs
- tests/NATS.Client.Core.Tests/NatsConnectionTest.cs
- tests/NATS.Client.Core.Tests/ProtocolTest.cs
- tests/NATS.Client.Core.Tests/RequestReplyTest.cs
- tests/NATS.Client.Core.Tests/SerializerTest.cs
- tests/NATS.Client.Core.Tests/SubscriptionTest.cs
- tests/NATS.Client.TestUtilities/Utils.cs
- tests/Nats.Client.Compat/Test.cs
Expose slightly lower level API for subscriptions to make it easier to build custom messaging patterns.
> Subscribe core method

- docs/documentation/jetstream/consume.md
- docs/documentation/jetstream/intro.md
- docs/documentation/jetstream/publish.md
- docs/documentation/key-value-store/intro.md
- docs/documentation/serialization.md
- docs/documentation/services/intro.md
- sandbox/Example.NativeAot/Program.cs
* Subscription API changes
* Serialization changes
* Also fixed example code
> Docs updates with API changes

- src/NATS.Client.Core/Internal/NatsReadProtocolProcessor.cs
- src/NATS.Client.Core/NatsConnection.cs
- src/NATS.Client.Core/NatsException.cs
- src/NATS.Client.Core/NatsOpts.cs
- tests/NATS.Client.Core.Tests/AuthErrorTest.cs
- tests/NATS.Client.TestUtilities/NatsServer.cs
- tests/NATS.Client.TestUtilities/NatsServerOpts.cs
Stop retrying after same two consecutive auth errors.
> Auth error retry handling

- src/NATS.Client.JetStream/INatsJSContext.cs
- src/NATS.Client.JetStream/INatsJSStream.cs
- src/NATS.Client.JetStream/Models/StreamListRequest.cs
- src/NATS.Client.JetStream/Models/StreamNamesRequest.cs
- src/NATS.Client.JetStream/Models/StreamNamesResponse.cs
- src/NATS.Client.JetStream/NatsJSContext.Consumers.cs
- src/NATS.Client.JetStream/NatsJSContext.Streams.cs
- src/NATS.Client.JetStream/NatsJSContext.cs
- src/NATS.Client.JetStream/NatsJSStream.cs
- tests/NATS.Client.JetStream.Tests/ConsumerConsumeTest.cs
- tests/NATS.Client.JetStream.Tests/ConsumerFetchTest.cs
- tests/NATS.Client.JetStream.Tests/ListTests.cs
- tests/NATS.Client.JetStream.Tests/ManageConsumerTest.cs
> List JetStream streams and consumers

- src/NATS.Client.JetStream/INatsJSNotification.cs
- src/NATS.Client.JetStream/Internal/NatsJSConsume.cs
- src/NATS.Client.JetStream/Internal/NatsJSFetch.cs
- src/NATS.Client.JetStream/Internal/NatsJSNotificationChannel.cs
- src/NATS.Client.JetStream/NatsJSConsumer.cs
- src/NATS.Client.JetStream/NatsJSOpts.cs
- src/NATS.Client.JetStream/NatsJSOrderedConsumer.cs
- tests/NATS.Client.JetStream.Tests/ErrorHandlerTest.cs
Notify users of events like timeouts while consuming messages.
/cc @Jarema
> JetStream consume error notifications

- src/NATS.Client.JetStream/Internal/NatsJSConsume.cs
- src/NATS.Client.JetStream/Internal/NatsJSFetch.cs
- src/NATS.Client.JetStream/Internal/NatsJSOrderedConsume.cs
This maybe causing issues with different logging frameworks.
> Removed logging object placeholders

- docs/documentation/jetstream/manage.md
- docs/documentation/security.md
- tests/NATS.Net.DocsExamples/JetStream/ManagingPage.cs
> Durable consumer docs

- src/NATS.Client.Services/INatsSvcServer.cs
- src/NATS.Client.Services/NatsSvcServer.cs
- tests/NATS.Client.Services.Tests/ServicesTests.cs
Added info and stats accessors to service object as they are returned from the service query APIs $SRV.INFO and STATS
> Added info and stats to services

- src/NATS.Client.JetStream/NatsJSContext.cs
During cluster reconnect we often get no-responders exceptions. This change makes sure JetStream publish method will retry in that case too.
> Handle JetStream publish no-responders

- .editorconfig
- src/NATS.Client.Core/INatsConnection.cs
- src/NATS.Client.Core/NatsConnection.cs
- src/NATS.Client.Core/NatsConnectionPool.cs
- src/NATS.Client.Core/NatsPooledConnection.cs
- src/NATS.Client.JetStream/INatsJSContext.cs
- tests/NATS.Client.Core.Tests/NatsConnectionPoolTest.cs
- tests/NATS.Client.Core.Tests/NatsConnectionTest.cs
- tests/NATS.Client.JetStream.Tests/NatsJSContextTest.cs
Fixes to ensure all public methods on the class are available on the interface for INatsConnection.
Test added to prove fixes
NatsConnectionPool adjustment to ensure pooled connections can't be accidentally disposed of.
> Suggested fixes to interfaces

- NATS.Client.sln
- src/NATS.Client.Hosting/NATS.Client.Hosting.csproj
- src/NATS.Client.Hosting/NatsHostingExtensions.cs
- tests/NATS.Client.Hosting.Tests/NATS.Client.Hosting.Tests.csproj
- tests/NATS.Client.Hosting.Tests/NatsHostingExtensionsTests.cs
PR for Issue #315 (Support Keyed DI services in .NET 8)
> Support Keyed DI services in .NET 8

- src/NATS.Client.Core/Internal/SslStreamConnection.cs
- src/NATS.Client.Core/NatsConnection.cs
- tests/NATS.Client.Core.Tests/TlsClientTest.cs
> TLS auth timeout

- version.txt
* Ordered consumer optimizations (#336)
* Addition of factories for better testability. (#330)
* Nullability review for models (#332)
* Support Keyed DI services in .NET 8 (#331)
* (not merged yet) TLS auth timeout (#339)
> Release 2.1.0-preview.3

- src/NATS.Client.Core/NatsConnection.cs
> Log connection failure as warning

- version.txt
* Async event handlers (#324)
* pipe reader: don't mark commands as consumed until pending=0 (#347)
* Log connection failure as warning (#343)
> Release 2.1.0-preview.4

- version.txt
* Fix unnecessary error log on dispose (#354)
* Updated interface to include Async events. (#353)
> Release 2.1.0-preview.5

- version.txt
* Send buffer changes (#346)
* Added deliver_group to consumer config (#366)
* Ping command as value task source (#358)
> Release 2.1.0-preview.6

- version.txt
* Send buffer fix (#380)
* Publish - avoid async state machine when possible (#373)
* Reject payloads over the threshold set by server (#378)
* Fix NatsSvcServer start time format so that it's no longer culture aware (#374)
* Expose Headers on NatsSvcMsg (#371)
> Release 2.1.0-preview.7

- src/NATS.Client.Hosting/NatsHostingExtensions.cs
- tests/NATS.Client.Hosting.Tests/NatsHostingExtensionsTests.cs
Keyed service was not returning different instances due to factory method not using the key.
> Hosting keyed services fixes

- tests/NATS.Client.Core.Tests/ProtocolTest.cs
- tests/NATS.Client.Core.Tests/SendBufferTest.cs
- tests/NATS.Client.Core.Tests/SlowConsumerTest.cs
- tests/NATS.Client.JetStream.Tests/ConsumerConsumeTest.cs
- tests/NATS.Client.JetStream.Tests/ConsumerSetupTest.cs
- tests/NATS.Client.TestUtilities/MockServer.cs
- tests/NATS.Client.TestUtilities/NatsServer.cs
fixed core tests. in JS Fetch_dispose_test still sometimes fails. I shall leave that to another PR
> Fix test flappers

- src/NATS.Client.Core/NatsHeaders.cs
- src/NATS.Client.KeyValueStore/NatsKVStore.cs
- tests/NATS.Client.Core.Tests/NatsHeaderTest.cs
- tests/NATS.Client.KeyValueStore.Tests/KeyValueStoreTest.cs
Resolves [480](https://github.com/nats-io/nats.net.v2/issues/480)
> Direct Message Header May Contain Multiple Subjects

- README.md
Adds NETStandard support to README.md
> Add NETStandard support to README.md

- version.txt
* Fix il2cpp error (take 2) (#548)
> Release 2.3.1-preview.2

- src/NATS.Client.Core/Commands/CommandWriter.cs
The previous version of the code had a potential issue where a fixed timeout was set for the readerTask in the CommandWriter class. This timeout has been removed since it's not practical to recover from a timeout situation here. The reader loop should finish quickly as it's governed by the cancellation token and won't be blocked by the socket connection.
* resolves #553
> Remove timeout from readerTask in CommandWriter

- src/NATS.Client.JetStream/Internal/NatsJSOrderedPushConsumer.cs
- src/NATS.Client.ObjectStore/NatsObjStore.cs
- tests/NATS.Client.ObjectStore.Tests/ObjectStoreTest.cs
Resolves https://github.com/nats-io/nats.net/issues/563
initially from https://github.com/nats-io/nats.net/pull/572
> Obj store empty list fixed

- version.txt
* Obj store empty list fixed (#578)
* KV never set duplicate window (#577)
* Resolved issue of ObjStore GetInfo MTime returning 0 (#567)
> Release 2.3.3-preview.2

- version.txt
* Fetch idle timeout default fix (#582)
> Release 2.3.3-preview.3

- version.txt
* Simplified NATS client (#607)
> Release 2.4.0-preview.2

- version.txt
* Add priority group options (overflow) (#743)
> Release 2.6.0-preview.2

- .github/workflows/docs.yml
- README.md
> Fix docs workflow

- version.txt
* Add KV marker reason check (#787)
> Release 2.6.0-preview.4

- src/NATS.Client.Core/Internal/NatsUri.cs
- src/NATS.Client.Core/NatsConnection.cs
- src/NATS.Client.Core/NatsOpts.cs
This reverts commit 30598aa3c571fixing merge 6dff0b64d9f2c4b0684e25aa45bb.
(fixing merge issues for socket factory)
> Revert "Fix proxy with TLS scenario with SocketConnectionFactory (#826)"

- version.txt
* Update KV per key TTL (#831)
> Release 2.6.0-preview.5

- NATS.Net.sln
- src/Directory.Build.props
- src/NATS.Client.Core/Internal/UserCredentials.cs
- src/NATS.Client.Core/NATS.Client.Core.csproj
- src/NATS.Client.Core/NatsMsg.cs
- src/NATS.Client.Hosting/NATS.Client.Hosting.csproj
- src/NATS.Client.JetStream/NATS.Client.JetStream.csproj
- src/NATS.Client.JetStream/NatsJSMsg.cs
- src/NATS.Client.KeyValueStore/NATS.Client.KeyValueStore.csproj
- src/NATS.Client.ObjectStore/NATS.Client.ObjectStore.csproj
- src/NATS.Client.ObjectStore/NatsObjStore.cs
- src/NATS.Client.Serializers.Json/NATS.Client.Serializers.Json.csproj
- src/NATS.Client.Services/NATS.Client.Services.csproj
- src/NATS.Client.Simplified/NATS.Client.Simplified.csproj
- src/NATS.Extensions.Microsoft.DependencyInjection/NATS.Extensions.Microsoft.DependencyInjection.csproj
- src/NATS.Net/NATS.Net.csproj
Increase usage of directory.build.props to reduce replication of properties across files. Have also move to suppression in code rather than global,
> Cleanup Csproj

- src/NATS.Client.Core/Internal/InboxSub.cs
Verified by the developer. see #884
* fixes #884
> Fix inbox collection was modified exception

- tools/site_src/documentation/intro.md
thanks @mrpmorris for the suggestion and examples.
> Update doc intro examples

- src/NATS.Client.Core/Internal/UserCredentials.cs
- src/NATS.Client.Core/NatsAuthOpts.cs
- tests/NATS.Client.TestUtilities/resources/configs/auth/user-invalid.creds
- tests/NATS.Slow.Tests/NatsConnectionTest.Auth.cs
> Add option to provide credentials directly without file
