- NATS.Client.sln.DotSettings
- src/NATS.Client.Core/Commands/ProtocolWriter.cs
- src/NATS.Client.Core/Commands/SubscribeCommand.cs
- src/NATS.Client.Core/INatsConnection.cs
- src/NATS.Client.Core/INatsSub.cs
- src/NATS.Client.Core/InboxSubscriber.cs
- src/NATS.Client.Core/NatsConnection.LowLevelApi.cs
- src/NATS.Client.Core/NatsConnection.Publish.cs
- src/NATS.Client.Core/NatsConnection.Subscribe.cs
- src/NATS.Client.Core/NatsConnection.cs
- src/NATS.Client.Core/NatsSub.cs
- src/NATS.Client.Core/NatsSubOpts.cs
- src/NATS.Client.Core/SubscriptionManager.cs
- tests/NATS.Client.Core.Tests/LowLevelApiTest.cs
- tests/NATS.Client.Core.Tests/ProtocolTest.cs
- tests/NATS.Client.Core.Tests/SubscriptionTest.cs
- tests/NATS.Client.Core.Tests/_NatsServer.cs
* Auto-unsubscribe on max-msgs, timeout and idle timeout
* Pass NatsMsg by ref to reduce copy overhead
* Hidden internal INatsSub API from public API using explicit interface implementations
> Auto-unsubscribe implementations and fixes

- src/Directory.Build.props
Assigning `Version` property has the following effect on the DLL files, if the `version.txt` (hence NuGet version) was `2.0.0-alpha.0` for example:
* *File version* and *Assembly version*: `2.0.0.0`
* *Product version*: `2.0.0-alpha.0`
> Have DLLs stamped with version too

- docs/documentation/queue.md
- docs/documentation/req-rep.md
- docs/documentation/toc.yml
- sandbox/BlazorWasm/Server/NatsServices/WeatherForecastService.cs
- sandbox/ConsoleApp/Program.cs
- src/NATS.Client.Core/NatsRequestExtensions.cs
- tests/NATS.Client.Core.Tests/NatsConnectionTest.cs
Removed Reply method and updated docs.
> Removed Reply extension method

- Directory.Build.props
- sandbox/BlazorWasm/Server/NatsServices/WeatherForecastService.cs
- sandbox/ConsoleApp/Program.cs
- sandbox/Example.Core.PublishHeaders/Program.cs
- sandbox/Example.Core.PublishModel/Program.cs
- sandbox/Example.Core.SubscribeHeaders/Program.cs
- sandbox/Example.Core.SubscribeModel/Program.cs
- sandbox/Example.Core.SubscribeQueueGroup/Program.cs
- sandbox/Example.Core.SubscribeRaw/Program.cs
- sandbox/NatsBenchmark/Program.cs
- src/NATS.Client.Core/Commands/CommandBase.cs
- src/NATS.Client.Core/Internal/BufferExtensions.cs
- src/NATS.Client.Core/Internal/INatsSub.cs
- src/NATS.Client.Core/Internal/InboxSubscriber.cs
- src/NATS.Client.Core/Internal/NatsReadProtocolProcessor.cs
- src/NATS.Client.Core/Internal/StringExtensions.cs
- src/NATS.Client.Core/Internal/SubscriptionManager.cs
- src/NATS.Client.Core/NatsConnection.Util.cs
- src/NATS.Client.Core/NatsConnection.cs
- src/NATS.Client.Core/NatsSub.cs
- tests/NATS.Client.Core.Tests/CancellationTest.cs
- tests/NATS.Client.Core.Tests/LowLevelApiTest.cs
- tests/NATS.Client.Core.Tests/NatsConnectionTest.QueueGroups.cs
- tests/NATS.Client.Core.Tests/NatsConnectionTest.cs
- tests/NATS.Client.Core.Tests/ProtocolTest.cs
- tests/NATS.Client.Core.Tests/RequestReplyTest.cs
- tests/NATS.Client.Core.Tests/_NatsServer.cs
- tests/NATS.Client.Core.Tests/_Utils.cs
Rough draft - `dotnet format` touched a bunch of files so sorry for the confusing diff
Removes `Sid` from `INatsSub`.  Also introduces `ISubscriptionManager`
`Sid` is an implementation detail of the default subscription manager.  For muxed subscriptions, such as `InboxSubscription`, an `InboxSubscriptionManager` could be used instead.
> remove Sid from INatsSub

- .github/workflows/release.yml
- .github/workflows/test.yml
* Minor typo in release workflow
* Bash is available in GitHub Windows runners
> Quick CI fixes

- src/NATS.Client.Core/Internal/InboxSub.cs
- src/NATS.Client.Core/Internal/SubscriptionManager.cs
- src/NATS.Client.Core/NatsRequestExtensions.cs
- tests/NATS.Client.Core.Tests/SubscriptionTest.cs
- Extension method to generate an Inbox - `nats.NewInbox()`
- Inbox Subscription manager support multiple Subscriptions on the same Inbox Subject
- Use `ConditionalWeakTable` to improve GC
- No cleanup/logging when Inbox Subs are GC'd without Disposal, but it doesn't really matter since there is no Unsub right now
I'm a little rusty on how to update ConcurrentDictionary with a value of another collection - check my implementation there.  Open to suggestions if there's a better pattern
> Inbox subscription iprovements

- src/NATS.Client.JetStream/Internal/JSErrorAwareJsonSerializer.cs
- src/NATS.Client.JetStream/JSContext.cs
- src/NATS.Client.JetStream/JSResponse.cs
- src/NATS.Client.JetStream/Models/ConsumerConfiguration.cs
- src/NATS.Client.JetStream/Models/ConsumerConfigurationAckPolicy.cs
- src/NATS.Client.JetStream/Models/ConsumerConfigurationDeliverPolicy.cs
- src/NATS.Client.JetStream/Models/ConsumerConfigurationReplayPolicy.cs
- src/NATS.Client.JetStream/Models/StreamConfiguration.cs
- src/NATS.Client.JetStream/Models/StreamConfigurationCompression.cs
- src/NATS.Client.JetStream/Models/StreamConfigurationDiscard.cs
- src/NATS.Client.JetStream/Models/StreamConfigurationRetention.cs
- src/NATS.Client.JetStream/Models/StreamConfigurationStorage.cs
- src/NATS.Client.JetStream/Models/StreamCreateResponse.cs
- tests/NATS.Client.JetStream.Tests/JetStreamTest.cs
- tests/NATS.Client.TestUtilities/NATS.Client.TestUtilities.csproj
- tests/NATS.Client.TestUtilities/NatsServer.cs
- tests/NATS.Client.TestUtilities/NatsServerOptions.cs
Basic use case APIs, publish and consume methods implemented. Consider this as the 'low-level' JetStream API where we can build our more familiar NATS Client Simplified JetStream API.
> JetStream basic usage

- src/NATS.Client.Core/NatsSub.cs
- src/NATS.Client.Core/NatsSubChannelOpts.cs
- src/NATS.Client.Core/NatsSubOpts.cs
There is value in being able to configure the `BoundedChannelOptions` for a given subscription (or series of subscriptions.)
For example, in cases where it is preferred to discard older data on a subscription, or cases where _only_ the most recent value is the one that is desired.
This PR also has the benefit, in the default case, we can just re-use our internal `BoundedChannelOptions` rather than passing a new one every time a new subscription is created (i.e. less memory allocation.)
Note that for the sake of reuse, this marked `internal static` on `NatsSub` rather than `private static`, since to have a separate static readonly on `NatsSub<T>` would both be unnecessary and would cause a new static to be allocated for every new `T` on `NatsSub<T>`.
> Allow Configuration of Subscription Channels

- tests/NATS.Client.TestUtilities/WaitSignal.cs
Make TaskCompletionSource used in wait signals run completions asynchronously to avoid potential deadlocks during test runs.
Note that this PR doesn't have any effect on the tests. It's not solving any current issues. It's just a precautionary fix for potential issues in general.
> Enable async for test wait signals

- src/NATS.Client.Core/Internal/SubscriptionManager.cs
- src/NATS.Client.Core/NatsConnection.cs
- src/NATS.Client.Core/NatsSubBase.cs
- tests/NATS.Client.Core.Tests/ProtocolTest.cs
Collect all subscription and additional commands to be prioritized when reconnecting. Additional commands will be important for JetStream consumers to issue pull requests in order to reestablish their state on the server.
> Reconnect NatsSub commands

- src/NATS.Client.Core/INatsConnection.cs
- src/NATS.Client.Core/INatsConnectionPool.cs
- src/NATS.Client.Core/NatsConnection.RequestReply.cs
- src/NATS.Client.Core/NatsConnectionPool.cs
- src/NATS.Client.Core/NatsRequestExtensions.cs
- src/NATS.Client.Core/NatsRequestManyExtensions.cs
- src/NATS.Client.Hosting/NatsHostingExtensions.cs
https://github.com/nats-io/nats.net.v2/issues/105
> Add INatsConnectionPool interface 

- src/NATS.Client.Core/INatsSerializer.cs
- src/NATS.Client.Core/INatsServerInfo.cs
- src/NATS.Client.Core/Internal/ClientOpts.cs
- src/NATS.Client.Core/Internal/ServerInfo.cs
- src/NATS.Client.Core/Internal/UserCredentials.cs
- src/NATS.Client.Core/NKeyPair.cs
- src/NATS.Client.Core/NatsAuthOpts.cs
- src/NATS.Client.Core/NatsConnection.cs
- src/NATS.Client.Core/NatsHeaderParser.cs
- src/NATS.Client.Core/NatsMsg.cs
- src/NATS.Client.Core/NatsOpts.cs
- src/NATS.Client.Core/NatsSubBase.cs
- src/NATS.Client.JetStream/NatsJSSubConsume.cs
- src/NATS.Client.JetStream/NatsJSSubFetch.cs
- tests/NATS.Client.Core.Tests/LowLevelApiTest.cs
- tests/NATS.Client.Core.Tests/NatsConnectionTest.Auth.cs
- tests/NATS.Client.Core.Tests/NatsHeaderTest.cs
- Consistently use `Nats` prefix on public classes
- Change `Nkey` -> `NKey`
> consistent Nats class prefix

- .github/workflows/perf.yml
- .github/workflows/test.yml
- src/NATS.Client.JetStream/Models/StreamSource.cs
- tests/NATS.Client.Core.Tests/RequestReplyTest.cs
- tests/NATS.Client.JetStream.Tests/ConsumerConsumeTest.cs
- tests/NATS.Client.TestUtilities/NatsServer.cs
* Resolves #133
* Test matrix changes
* Test fixes!
> Added subject transforms to stream source config

- .github/workflows/test.yml
- src/NATS.Client.JetStream/Internal/NatsJSConsume.cs
- src/NATS.Client.JetStream/NatsJSConsumer.cs
- src/NATS.Client.JetStream/NatsJSMsg.cs
- tests/NATS.Client.Core.Tests/RequestReplyTest.cs
- tests/NATS.Client.JetStream.Tests/ManageStreamTest.cs
Mainly additional debugging and synchronization around pending numbers in consume.
* Added locking around pending
* More debugging info for pull requests
* Timeouts for potentially hanging tests
> Fixing test flappers

- sandbox/MicroBenchmark/MicroBenchmark.csproj
- sandbox/MicroBenchmark/NewInboxBenchmarks.cs
- sandbox/MicroBenchmark/Program.cs
- src/NATS.Client.Core/Internal/NuidWriter.cs
- src/NATS.Client.Core/Internal/SubscriptionManager.cs
- src/NATS.Client.Core/NATS.Client.Core.csproj
- src/NATS.Client.Core/NatsConnection.RequestReply.cs
- src/NATS.Client.Core/NatsConnection.RequestSub.cs
- src/NATS.Client.Core/NatsConnection.cs
- tests/NATS.Client.Core.Tests/NuidWriterTests.cs
Fixes #34 
```
| Method               | Job           | Runtime       | Mean     | Error    | StdDev   | Median   | Ratio | RatioSD | Gen0   | Allocated | Alloc Ratio |
|--------------------- |-------------- |-------------- |---------:|---------:|---------:|---------:|------:|--------:|-------:|----------:|------------:|
| TryWriteNuid         | .NET 6.0      | .NET 6.0      | 31.00 ns | 0.365 ns | 0.305 ns | 31.06 ns |  0.99 |    0.03 |      - |         - |          NA |
| NewInbox_ShortPrefix | .NET 6.0      | .NET 6.0      | 51.74 ns | 1.078 ns | 1.476 ns | 51.90 ns |  1.64 |    0.07 | 0.0612 |     128 B |          NA |
| NewInbox_LongPrefix  | .NET 6.0      | .NET 6.0      | 76.69 ns | 1.568 ns | 2.662 ns | 76.52 ns |  2.44 |    0.12 | 0.1988 |     416 B |          NA |
| TryWriteNuid …
```
> Implement NUID

- NATS.Client.sln
- sandbox/Example.TlsFirst/Example.TlsFirst.csproj
- sandbox/Example.TlsFirst/Program.cs
- src/NATS.Client.Core/Internal/NatsUri.cs
- src/NATS.Client.Core/Internal/SslStreamConnection.cs
- src/NATS.Client.Core/Internal/TlsCerts.cs
- src/NATS.Client.Core/NatsConnection.cs
- src/NATS.Client.Core/NatsTlsOpts.cs
- tests/NATS.Client.Core.Tests/NatsConnectionTest.cs
- tests/NATS.Client.Core.Tests/TlsFirstTest.cs
- tests/NATS.Client.TestUtilities/NatsServer.cs
- tests/NATS.Client.TestUtilities/NatsServerOpts.cs
- tests/NATS.Client.TestUtilities/WaitSignal.cs
Currently only supported in server PR https://github.com/nats-io/nats-server/pull/4642
> TLS first connection

- src/NATS.Client.Core/INatsSerializer.cs
- src/NATS.Client.Core/NatsMemoryOwner.cs
- src/NATS.Client.ObjectStore/NatsObjStore.cs
- tests/NATS.Client.KeyValueStore.Tests/NatsKVWatcherTest.cs
- tests/NATS.Client.Perf/Program.cs
Adapts `MemoryOwner<T>` from `CommunityToolkit.HighPerformance` ([docs](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/high-performance/memoryowner), [source](https://github.com/CommunityToolkit/dotnet/blob/v8.2.1/src/CommunityToolkit.HighPerformance/Buffers/MemoryOwner%7BT%7D.cs))
Changes it to a struct for non-nullable de-serialization - this was the main motivation
> add NatsMemoryOwner

- src/NATS.Client.JetStream/NatsJSContext.Streams.cs
- src/NATS.Client.KeyValueStore/NatsKVContext.cs
- tests/NATS.Client.JetStream.Tests/ManageStreamTest.cs
This PR adds the StreamInfoRequest to GetStream
Note: This option is not present in the nats go client. To get the required StreamInfo in the nats go client they have the `JetStreamManagement`. I added it to this method, because nats.net.v2 doesn't have the `JetStreamManagement` at the moment.
We need it to figure out the subjects inside a stream. If there is a better way, I'm happy to hear about this.
> Add StreamInfo request to GetStream

- src/NATS.Client.JetStream/Models/StreamState.cs
This PR marks the Subjects property as nullable. Subjects gets only set when StreamInfo has a subjects filter set and nats is initialized.
> Mark StreamState Subjects as nullable

- src/NATS.Client.Core/NatsConnection.Subscribe.cs
SubscribeInternalAsync() method was left public by mistake.
> Hide subscribe internal method

- src/NATS.Client.Core/NatsConnection.cs
- src/NATS.Client.JetStream/Internal/NatsJSConsume.cs
Keep the idle heartbeat timer ticking so if all else fails, it will try to send pull requests as long as we have an open connection. We also made a preventive change to connection state management making it thread safe since we suspect there may be race conditions on ARM processors for example.
(Issue was found during failground testing: consumer stopped pulling after about 20 hours)
> JetStream consume idle heartbeat fix

- src/NATS.Client.Core/NatsConnection.Subscribe.cs
- tests/NATS.Client.Core.MemoryTests/NatsSubTests.cs
The issue was happening with Perf tests hanging. It turns out when subscription was handled within async iterator we loose a reference to the subscription potentially because it's in a using as well. This solution makes sure the connection object will keep a reference so subscription object won't be collected because of the weak ref in the subscription manager. Also we don't need to worry about disposing the subscription now because as soon as the loop exits it will be disposed.
> Async iterator subscription memory fix

- sandbox/Example.JetStream.PullConsumer/Program.cs
- src/NATS.Client.JetStream/INatsJSConsumer.cs
- src/NATS.Client.JetStream/INatsJSContext.cs
- src/NATS.Client.JetStream/NatsJSConsumer.cs
- src/NATS.Client.JetStream/NatsJSContext.Consumers.cs
- src/NATS.Client.JetStream/NatsJSOrderedConsumer.cs
- src/NATS.Client.JetStream/NatsJSStream.cs
- tests/NATS.Client.Core.MemoryTests/NatsSubTests.cs
- tests/NATS.Client.JetStream.Tests/ConsumerConsumeTest.cs
- tests/NATS.Client.JetStream.Tests/ConsumerFetchTest.cs
- tests/NATS.Client.JetStream.Tests/JetStreamTest.cs
Defined JetStream public interfaces to indicate what is supported and help with dependency injection and unit testing scenarios.
contributes to #105 
resolves #31
> JetStream public interfaces

- src/NATS.Client.KeyValueStore/INatsKVContext.cs
- src/NATS.Client.KeyValueStore/INatsKVStore.cs
- src/NATS.Client.KeyValueStore/NatsKVContext.cs
- src/NATS.Client.KeyValueStore/NatsKVStore.cs
- tests/NATS.Client.Core.MemoryTests/NatsSubTests.cs
- tests/NATS.Client.KeyValueStore.Tests/NatsKVWatcherTest.cs
Defined Key Value Store public interfaces to indicate what is supported and help with dependency injection and unit testing scenarios.
contributes to #105
> Key Value store interfaces

- src/NATS.Client.Core/Internal/SslStreamConnection.cs
- src/NATS.Client.Core/Internal/TcpConnection.cs
- src/NATS.Client.Core/NatsConnection.cs
When connection fails because of SSL validation checks the exception doesn't tell you that (just says could not connect). If the user enables logging then they'd at least be able to see if the connection failed because of TLS validation errors and why.
> TLS validation error logging on connection

- src/NATS.Client.Core/NatsConnection.Subscribe.cs
- src/NATS.Client.JetStream/Internal/NatsJSOrderedConsume.cs
- src/NATS.Client.JetStream/NatsJSConsumer.cs
- src/NATS.Client.JetStream/NatsJSContext.cs
- src/NATS.Client.JetStream/NatsJSException.cs
- src/NATS.Client.JetStream/NatsJSOrderedConsumer.cs
- tests/NATS.Client.Core.MemoryTests/NatsConsumeTests.cs
- tests/NATS.Client.Testing.Failground/OrderedConsumeTest.cs
Because ordered consume operations use ephemeral consumers it's important to be able to create new consumers when things go wrong. There are two major events that might strongly indicate we won't be able to find our consumer on the server: disconnects and idle heartbeat timeouts.
With this approach introduced with this fix, we recreate the consumer on server disconnects and idle heartbeat timeouts, making sure the consumer can carry on from where it's left off (sequence state is maintained when this happens).
Justification for large code duplication: NatsJSOrderedConsume.cs is a copy of NatsJSConsume.cs subscription class. Reason for this is to maintain stability of the normal consumer since the main behaviour is fairly different. There is also a chance the behaviours might diverge even …
> JetStream ordered consume stability fixes

- tests/NATS.Client.JetStream.Tests/ConsumerNextTest.cs
- tests/NATS.Client.JetStream.Tests/OrderedConsumerTest.cs
Some tests are failing because of cancellation timeouts. Moved timeout tokens after server creations since that might take longer when running test suits.
> Test flapper fixes

- src/NATS.Client.JetStream/Internal/NatsJSConstants.cs
- src/NATS.Client.JetStream/NatsJSMsg.cs
- tests/NATS.Client.JetStream.Tests/DoubleAckNakDelayTests.cs
* Messages received by the consumer can be acknowledged optionally asking the server acknowledging the message acknowledgment.
* Messages can be 'rejected' (-NAK) with a delay.
> JetStream double ACK and NAK delay

- src/NATS.Client.Core/NatsConnection.cs
- src/NATS.Client.Core/NatsOpts.cs
- tests/NATS.Client.Core.Tests/ConnectionRetryTest.cs
To help minimize the impact on the servers during failures.
> Reconnect backoff

- src/NATS.Client.KeyValueStore/NatsKVConfig.cs
- src/NATS.Client.KeyValueStore/NatsKVContext.cs
- src/NATS.Client.KeyValueStore/NatsKVStore.cs
- src/NATS.Client.ObjectStore/NatsObjConfig.cs
- src/NATS.Client.ObjectStore/NatsObjContext.cs
- src/NATS.Client.ObjectStore/NatsObjStore.cs
- tests/NATS.Client.KeyValueStore.Tests/KeyValueStoreTest.cs
- tests/NATS.Client.ObjectStore.Tests/ObjectStoreTest.cs
- tests/NATS.Client.TestUtilities/NatsServer.cs
contributes to nats-io/nats-architecture-and-design#253
> Key/Value and Object Store compression

- NATS.Client.sln.DotSettings
- sandbox/Example.JetStream.PullConsumer/Program.cs
- src/NATS.Client.JetStream/Internal/NatsJSJsonSerializer.cs
- src/NATS.Client.JetStream/Internal/NatsJSOrderedPushConsumer.cs
- src/NATS.Client.JetStream/Models/ConsumerConfig.cs
- src/NATS.Client.JetStream/Models/ConsumerConfigAckPolicy.cs
- src/NATS.Client.JetStream/Models/ConsumerConfigDeliverPolicy.cs
- src/NATS.Client.JetStream/Models/ConsumerConfigReplayPolicy.cs
- src/NATS.Client.JetStream/Models/StreamConfig.cs
- src/NATS.Client.JetStream/Models/StreamConfigCompression.cs
- src/NATS.Client.JetStream/Models/StreamConfigDiscard.cs
- src/NATS.Client.JetStream/Models/StreamConfigRetention.cs
- src/NATS.Client.JetStream/Models/StreamConfigStorage.cs
- src/NATS.Client.JetStream/NatsJSContext.Consumers.cs
- src/NATS.Client.JetStream/NatsJSOpts.cs
- src/NATS.Client.JetStream/NatsJSOrderedConsumer.cs
- src/NATS.Client.KeyValueStore/Internal/NatsKVWatcher.cs
- src/NATS.Client.KeyValueStore/NatsKVContext.cs
- src/NATS.Client.KeyValueStore/NatsKVStore.cs
- src/NATS.Client.ObjectStore/NatsObjContext.cs
- src/NATS.Client.ObjectStore/NatsObjStore.cs
- tests/NATS.Client.CheckNativeAot/Program.cs
- tests/NATS.Client.Core.MemoryTests/NatsConsumeTests.cs
- tests/NATS.Client.JetStream.Tests/EnumJsonTests.cs
- tests/NATS.Client.JetStream.Tests/JetStreamTest.cs
- tests/NATS.Client.KeyValueStore.Tests/KeyValueStoreTest.cs
- tests/NATS.Client.ObjectStore.Tests/ObjectStoreTest.cs
System.Text.Json serializer has some difficult settings serializing enums. Before we just relied on unconventional property names in code but proper way is to use PascalCase. Unfortunately the JSON options also did not allow snake_case conversion also I didn't want to force System.Text.Json v8 onto net6.0 targets (if that supports it). Hence we now have a JetStream specific JSON enum convertor.
> JetStream enum PascalCase serializer

- src/NATS.Client.JetStream/INatsJSContext.cs
- src/NATS.Client.JetStream/INatsJSStream.cs
- src/NATS.Client.JetStream/Internal/NatsJSJsonSerializer.cs
- src/NATS.Client.JetStream/Models/StreamUpdateRequest.cs
- src/NATS.Client.JetStream/NatsJSContext.Streams.cs
- src/NATS.Client.JetStream/NatsJSStream.cs
- tests/NATS.Client.JetStream.Tests/ManageStreamTest.cs
StreamUpdateRequest was a placeholder class inheriting StreamConfig and adding no value to it. Using StreamUpdateRequest in update stream methods and StreamConfig in creation method was inconsistent and it was causing unnecessary object creation in some cases forcing the end developer to map everything from config object.
> Removed redundant StreamUpdateRequest class

- src/NATS.Client.JetStream/Internal/NatsJSConsume.cs
- src/NATS.Client.JetStream/Internal/NatsJSFetch.cs
- tests/NATS.Client.JetStream.Tests/DoubleAckTest.cs
Increase consume and fetch channel size to avoid blocking the socket reads for other operations. I think we have done this change before but somehow reverted back during merges perhaps.
> Increase consume and fetch channel size

- src/NATS.Client.JetStream/NatsJSMsg.cs
- tests/NATS.Client.JetStream.Tests/ConsumerConsumeTest.cs
- tests/NATS.Client.JetStream.Tests/ConsumerFetchTest.cs
- tests/NATS.Client.JetStream.Tests/CustomSerializerTest.cs
- tests/NATS.Client.JetStream.Tests/DoubleAckTest.cs
When a custom serializer used JetStream msg ACKs are still being serialized using the custom serializer which is resulting in +ACK being sent to the server with a distorted format. Now we just used the NATS default serializer on message ACKs to format the +ACK/NAK/etc. payload correctly.
ConsumerFetchTest.cs was also passing for the wrong reasons, which is also fixed. Plus minor format issue fixed.
> Fixed JetStream ACK custom serialization

- src/NATS.Client.Core/Internal/ClientOpts.cs
- src/NATS.Client.Core/NatsConnection.RequestReply.cs
- src/NATS.Client.Core/NatsException.cs
- src/NATS.Client.Core/NatsMsg.cs
- src/NATS.Client.Core/NatsOpts.cs
- tests/NATS.Client.Core.Tests/NatsConnectionTest.cs
- tests/NATS.Client.Core.Tests/RequestReplyTest.cs
This solves #258
* Feature can be enabled via. `NatsOpts.NoResponders` (defaults to `false` like before the PR)
* Throws a new `NatsNoRespondersException` if triggered cia. `RequestAsync`, but not if triggered via `PublishAsync`.
* A normal subscriber that receives a message due to `no_responders`, in case the client is using his own `request-reply` mechanism through PubSub and `reply_to`, does NOT throw an exception but the subscriber receives an empty message with `msg.Headers.Code` equal to `503`.
* We could also have this throw an exception but I felt it didn't make sense outside of `RequestAsync` but that's open for discussion. It could even be another configuration value for NatsOpts (`bool ThrowOnNoResponders`) so let's discuss that.
* Added tests for both `RequestAsync` and custom …
> Adding support for the no_responders feature.

- .github/workflows/docs.yml
- .github/workflows/release.yml
That way we can update documentation in between releases as well as have more frequent preview releases without documentation updates.
> Separate docs updates and release workflows

- sandbox/Example.ObjectStore/Program.cs
- src/NATS.Client.ObjectStore/INatsObjContext.cs
- src/NATS.Client.ObjectStore/NatsObjContext.cs
- src/NATS.Client.ObjectStore/NatsObjStore.cs
- tests/NATS.Client.CheckNativeAot/Program.cs
- tests/NATS.Client.ObjectStore.Tests/ObjectStoreTest.cs
- tests/NATS.Client.ObjectStore.Tests/WatcherTest.cs
- tests/NATS.Net.DocsExamples/ObjectStore/IntroPage.cs
- tests/Nats.Client.Compat/ObjectStoreCompat.cs
* Fixed watcher not to exit after receiving initial set of objects. Introduced a new option to accomodate for that behaviour rather than returning null for example.
* Also fixed the method naming to be affixed 'Async'.
**Breaking change:**
* Renamed `INatsObjContext` `CreateObjectStore()` method to `CreateObjectStoreAsync()`
> Watcher fix and API naming fix

- src/NATS.Client.Core/INatsError.cs
- src/NATS.Client.Core/NatsConnection.cs
- src/NATS.Client.Core/NatsOpts.cs
- src/NATS.Client.Core/NatsSub.cs
- tests/NATS.Client.Core.MemoryTests/NatsSubTests.cs
- tests/NATS.Client.Core.Tests/SlowConsumerTest.cs
- tests/NATS.Client.Perf/Program.cs
Slow consumers are subscriptions which are unable to process their messages fast enough. When the internal subscription channel is full oldest messages should be dropped and new messages should continued to be processed. This is aligned with NATS at most once delivery.
See also https://docs.nats.io/running-a-nats-service/nats_admin/slow_consumers
> Added slow consumer events

- src/NATS.Client.Core/Internal/TlsCerts.cs
- src/NATS.Client.Core/NatsConnection.cs
- src/NATS.Client.Core/NatsTlsOpts.cs
- tests/NATS.Client.Core.Tests/TlsCertsTest.cs
- tests/NATS.Client.TestUtilities/NatsServer.cs
Note - PR is to branch opened for #283 
Suggestion to move string-based PEM loading to callbacks, which will enable other functionality in callbacks too - different cert formats, private keys with passwords, load from external store, etc
> move string-based PEM loading to callbacks

- src/NATS.Client.Core/NatsConnection.RequestReply.cs
- src/NATS.Client.Core/NatsMsg.cs
- src/NATS.Client.Core/NatsSubBase.cs
- src/NATS.Client.Core/NatsSubOpts.cs
- src/NATS.Client.JetStream/NatsJSContext.cs
- tests/NATS.Client.CheckNativeAot/Program.cs
Handles No Responders in `NatsSubBase`, pre-de-serialization
Also handles `StopOnEmptyMsg`
This prevents the library from ever needing to check `msg.Data` for an Empty value
> handle no responders in NatsSubBase

- src/NATS.Client.Core/Internal/SslStreamConnection.cs
- src/NATS.Client.Core/NatsTlsOpts.cs
- tests/NATS.Client.Core.Tests/TlsClientTest.cs
Looks like OCSP must-staple support is implemented in .NET7 and should be in .NET8. Not sure if .NET6 received a patch as well. https://github.com/dotnet/runtime/issues/33377
> TLS Check Certificate Revocation option

- sandbox/Example.Core.PublishHeaders/Example.Core.PublishHeaders.csproj
- sandbox/Example.Core.PublishHeaders/Program.cs
- sandbox/Example.Core.PublishModel/Example.Core.PublishModel.csproj
- sandbox/Example.Core.PublishModel/Program.cs
- sandbox/Example.Core.SubscribeHeaders/Example.Core.SubscribeHeaders.csproj
- sandbox/Example.Core.SubscribeHeaders/Program.cs
- sandbox/Example.Core.SubscribeModel/Example.Core.SubscribeModel.csproj
- sandbox/Example.Core.SubscribeModel/Program.cs
Currently the example projects `Example.Core.PublishModel`, `Example.Core.SubscribeModel`, `Example.Core.PublishHeaders` and `Example.Core.SubscribeHeaders` are not working because the default serializer can not handle the custom `Bar` type. To make the programs work, we need to provide a serializer for that type. 
To achieve this, i added a project reference to `Nats.Client.Serializers.Json` and configured the `NatsJsonSerializerRegistry` as SerializerRegistry in the mentioned projects.
The same could be achieved by using the AOT ready `NatsJsonContextSerializer` but with we would need to create a custom `JsonSerializerContext` for the `Bar` type in every project. To keep the required code as small as possible, i chose the reflection based serializer.
> Fixed serialization problem in PublishModel/PublishHeaders examples

- src/NATS.Client.Services/Internal/SvcListener.cs
- tests/NATS.Client.Services.Tests/NATS.Client.Services.Tests.csproj
- tests/NATS.Client.Services.Tests/ServicesSerializationTest.cs
- tests/NATS.Client.TestUtilities/Utils.cs
This is necessary when the default serializer isn't using a Raw serialization for NatsMemory type which is used by the service listener.
> Explicitly set service listener serialization

- src/NATS.Client.JetStream/NatsJSMsg.cs
This PR addresses #312 , exposing the ReplyTo property on NatsJSMsg.
> Expose ReplyTo on NatsJSMsg

- src/NATS.Client.ObjectStore/NatsObjStore.cs
- tests/NATS.Client.ObjectStore.Tests/ObjectStoreTest.cs
Since object names are encoded when stores they can be anything as long as not empty.
> Object store name check fix

- Directory.Build.props
- sandbox/MicroBenchmark/CommandConstantsBench.cs
- sandbox/MicroBenchmark/MicroBenchmark.csproj
- src/NATS.Client.Core/Commands/ProtocolWriter.cs
Resolves #319 
New MicroBenchmark shows benefit in writing UInt 16/32/64.  Maybe because I am on a newer CPU on this box?  :man_shrugging: Looks like it is worth changing though
```
BenchmarkDotNet v0.13.12, Ubuntu 22.04.3 LTS (Jammy Jellyfish)
AMD Ryzen 5 3600, 1 CPU, 12 logical and 6 physical cores
.NET SDK 8.0.101
[Host]   : .NET 8.0.1 (8.0.123.58001), X64 RyuJIT AVX2
ShortRun : .NET 8.0.1 (8.0.123.58001), X64 RyuJIT AVX2
Job=ShortRun  IterationCount=3  LaunchCount=1  
WarmupCount=3  
```
| Method            | Iter    | Size | Mean       | Error     | StdDev  | Allocated |
|------------------ |-------- |----- |-----------:|----------:|--------:|----------:|
| **PubCopy**           | **1000000** | **2**    |   **368.9 μs** | **109.60 μs** | **6.01 μs** |         **-** |
| PubSetIndex …
> micro-optimizations in ProtocolWriter

- src/NATS.Client.Core/NatsConnection.cs
- src/NATS.Client.JetStream/INatsJSContextFactory.cs
- src/NATS.Client.JetStream/Internal/NatsJSOrderedConsume.cs
- src/NATS.Client.JetStream/NatsJSMsg.cs
- src/NATS.Client.JetStream/NatsJSOrderedConsumer.cs
- tests/NATS.Client.JetStream.Tests/NatsJsContextFactoryTest.cs
- tests/NATS.Client.KeyValueStore.Tests/NatsKVContextFactoryTest.cs
- tests/NATS.Client.ObjectStore.Tests/NatsObjContextFactoryTest.cs
* Pull channel optimization
* Reduce consume method complexity
With this fix ordered consumer message rate goes up x2.
> Ordered consumer optimizations

- src/NATS.Client.Core/Commands/ProtocolWriter.cs
- src/NATS.Client.Core/Internal/NatsPipeliningWriteProtocolProcessor.cs
- tests/NATS.Client.Core.Tests/ProtocolTest.cs
- tests/NATS.Client.TestUtilities/InMemoryTestLoggerFactory.cs
Includes test from #346 (e90d588d9c2732ffd64729d177bdfe93646e9505) - thanks for recreating @mtmk 
Previously, commands that were partially trimmed but not sent had marked their data from the pipe reader as Consumed.  On a Reconnect, the same amount of data would get Consumed again.
Refactors the Pipe Reader to only mark data as consumed once an entire command has been processed (pending == 0)
Also adds a bunch of comments to help explain the flow
>  pipe reader: don't mark commands as consumed until pending=0 

- src/NATS.Client.Core/INatsConnection.cs
- tests/NATS.Client.Core.Tests/NatsConnectionTest.cs
- tests/NATS.Client.JetStream.Tests/NatsJsContextFactoryTest.cs
added ConnectionDisconnected, ConnectionOpened, ReconnectFailed, and MessageDropped events to the INatsConnection interface.
> Updated interface to include Async events.

- src/NATS.Client.Core/NatsConnection.cs
Ignore operation cancel error in event handling loop since it'd be cancelled on connection dispose.
This is causing unclean server shutdown in some cases.
original thread https://natsio.slack.com/archives/C1V81FKU6/p1706128132853999
cc @mnmr
> Fix unnecessary error log on dispose

- sandbox/MicroBenchmark/PingBench.cs
- src/NATS.Client.Core/Commands/PingCommand.cs
- src/NATS.Client.Core/Internal/NatsReadProtocolProcessor.cs
- src/NATS.Client.Core/NatsConnection.Ping.cs
- src/NATS.Client.Core/NatsConnection.cs
main:
| Method       | Iter | Mean     | Error     | StdDev  | Allocated |
|------------- |----- |---------:|----------:|--------:|----------:|
| PublishAsync | 64   | 165.9 us |  39.41 us | 2.16 us |     488 B |
| PublishAsync | 512  | 375.1 us |  81.65 us | 4.48 us |     488 B |
| PublishAsync | 1024 | 607.0 us | 152.22 us | 8.34 us |     488 B |
| Method    | Iter | Mean       | Error      | StdDev    | Allocated |
|---------- |----- |-----------:|-----------:|----------:|----------:|
| PingAsync | 64   |   6.915 ms |  0.6316 ms | 0.0346 ms |   17.7 KB |
| PingAsync | 512  |  55.737 ms | 33.2913 ms | 1.8248 ms | 140.31 KB |
| PingAsync | 1024 | 114.085 ms | 30.5851 ms | 1.6765 ms |  280.4 KB |
This PR:
| Method       | Iter | Mean     | Error    | StdDev  | Allocated |
|------------- …
> Ping command as value task source

- .github/workflows/perf.yml
- .github/workflows/test.yml
When using binaries.nats.dev, branch names `latest` and `main` were both picking up the same development version. Also release now picks the latest 2.9.x
Now we test for: 2.9, 2.10 and main
**Edit:** I was wrong, this isn't working. We still need to find a way to test 2.10.x latest. `main` and `latest` tags are giving us the same binary.
**Edit2:**: We'll use the exact versions until above tags are supported by binaries service.
> Text matrix CI server versions

- src/NATS.Client.JetStream/Models/ConsumerConfig.cs
- tests/NATS.Client.JetStream.Tests/ConsumerSetupTest.cs
Added the missing property for `deliver_group`.
Note: ConsumerConfig was generated from this schema I believe, which doesn't have deliver_group defined https://github.com/nats-io/jsm.go/blob/main/schemas/jetstream/api/v1/consumer_create_request.json#L140
> Added deliver_group to consumer config

- sandbox/MicroBenchmark/PublishParallelBench.cs
- sandbox/MicroBenchmark/PublishSerialBench.cs
Add a micro benchmark for publishing in parallel
Uses JSON serialization in an attempt to make serialization more CPU intensive
> MicroBenchmark for PublishParallel

- src/NATS.Client.Core/Commands/CommandWriter.cs
- tests/NATS.Client.Core.Tests/ConnectionRetryTest.cs
we have no idea if bytes in send buffer were actually sent on a failed `SendAsync`
> throw away bytes in send buffer after a failed send

- src/NATS.Client.Services/NatsSvcMsg.cs
- tests/NATS.Client.Services.Tests/ServicesTests.cs
Thi pr adds the following
* Exposes Heades on NatsSvcMsg (forwarded from the underlying NastMsg)
* A simple service test to make sure headers gets passed to and from service endpoints.
Fixes #370
> Expose Headers on NatsSvcMsg

- src/NATS.Client.Services/NatsSvcServer.cs
- tests/NATS.Client.Services.Tests/ServicesTests.cs
Changes the started time format in NatsSvcServer to `yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffff'Z'`  note the  added ' (ticks)  in  the format, this makes sure its NOT affected by current culture, see  [DateTimeFormatInfo.UniversalSortableDateTimePattern Property](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.datetimeformatinfo.universalsortabledatetimepattern?view=net-8.0) on how the "iso" format is specified in .Net
Fixes #372
> Fix NatsSvcServer start time format so that it's no longer culture aware

- src/NATS.Client.Core/Commands/CommandWriter.cs
- src/NATS.Client.Core/Commands/PriorityCommandWriter.cs
- src/NATS.Client.Core/NatsConnection.cs
- tests/NATS.Client.Core.Tests/ProtocolTest.cs
- tests/NATS.Client.TestUtilities/MockServer.cs
Proactively reject payloads over the threshold set by server.
Go client reference:
https://github.com/nats-io/nats.go/blob/f42d2be72a8e21f8f684f002a870eefb852ec937/nats.go#L3761
> Reject payloads over the threshold set by server

- src/NATS.Client.Core/Commands/CommandWriter.cs
- src/NATS.Client.Core/NatsOpts.cs
- tests/NATS.Client.Core.Tests/CancellationTest.cs
Brings back optimizations from prior to #346 
- Logic to skip async state machine when possible
- Locks switched back from channel-based to semaphore-based, but it appears they are faster
- Selective send memory consolidation
- Bigger send buffer sizes
Performed some benchmarks on Linux:
`main`:
```
Completed: 9999701, Awaited: 299
1,412,795 msgs/sec ~ 172.46 MB/sec
```
This PR:
```
Completed: 9999980, Awaited: 20
2,688,705 msgs/sec ~ 328.21 MB/sec
```
So around 1.9x more throughput.
`main`:
| Method       | Iter | Mean     | Error      | StdDev    | Allocated |
|------------- |----- |---------:|-----------:|----------:|----------:|
| **PublishAsync** | **64**   | **126.0 μs** |   **246.1 μs** |  **13.49 μs** |     **360 B** |
| **PublishAsync** | **512**  | **584.0 μs** | **2,328.1 μs** …
> Publish - avoid async state machine when possible

- src/NATS.Client.Core/Commands/CommandWriter.cs
adds reset to partial send buffer counter
> rework partial send buffer counter

- src/NATS.Client.Core/Commands/CommandWriter.cs
- tests/NATS.Client.Core.Tests/ConnectionRetryTest.cs
- tests/NATS.Client.Core.Tests/ProtocolTest.cs
- tests/NATS.Client.Core.Tests/SendBufferTest.cs
- tests/NATS.Client.TestUtilities/InMemoryTestLoggerFactory.cs
- tests/NATS.Client.TestUtilities/MockServer.cs
If server drops the connection halfway through sending a large message pipelines reader was not recovering after reconnect. With this fix we consider the pending message sent if there were any socket send errors.
PS I could not reproduce the issue connecting to nats-server (hence used the mock server) but the error can be reproduced if proactive max_payload check is commented out. Just try to publish a payload larger than 1MB then try to publish or ping after that. Even though client reconnects you'd see pipeline exceptions: `System.InvalidOperationException: The examined position cannot be less than the previously examined position.`
> Send buffer fix

- src/NATS.Client.Core/Commands/CommandWriter.cs
- src/NATS.Client.Core/NatsOpts.cs
Changed buffer defaults from 1m to 64k to avoid allocating in LOH for better GC performance and memory utilisation.
* Changed pipeline segment size to be configured based on write buffer size
* Used `PoolingAsyncValueTaskMethodBuilder` for publish to reduce allocations
| Method       | Iter | BufferSize | Mean     | Error     | StdDev  | Allocated |
|------------- |----- |----------- |---------:|----------:|--------:|----------:|
| PublishAsync | 64   | 65536      | 143.8 us |  59.51 us | 3.26 us |     372 B |
| PublishAsync | 64   | 1048576    | 155.8 us |  21.27 us | 1.17 us |     339 B |
| PublishAsync | 512  | 65536      | 299.2 us | 111.81 us | 6.13 us |     338 B |
| PublishAsync | 512  | 1048576    | 310.9 us |  99.12 us | 5.43 us |     359 B |
| PublishAsync | 1024 | 65536      | …
> Buffer defaults avoiding LOH

- sandbox/MicroBenchmark/NKeyBench.cs
- sandbox/MicroBenchmark/Sha512Bench.cs
- tests/NATS.Client.Core.Tests/NKeyTests.cs
In preparation for replacing the internal implementation of Sha512 with the Sha512 built in to the .Net framework.
The current numbers for reference:
```shell
BenchmarkDotNet v0.13.12, macOS Sonoma 14.3.1 (23D60) [Darwin 23.3.0]
Apple M2 Pro, 1 CPU, 12 logical and 12 physical cores
.NET SDK 8.0.101
[Host]   : .NET 8.0.1 (8.0.123.58001), Arm64 RyuJIT AdvSIMD
ShortRun : .NET 8.0.1 (8.0.123.58001), Arm64 RyuJIT AdvSIMD
Job=ShortRun  IterationCount=3  LaunchCount=1  
WarmupCount=3  
| Method     | Iter | Mean     | Error   | StdDev  | Gen0     | Allocated |
|----------- |----- |---------:|--------:|--------:|---------:|----------:|
| NKeyCreate | 5000 | 142.9 ms | 5.23 ms | 0.29 ms | 500.0000 |   4.08 MB |
| Method     | Iter | DataSize | Mean      | Error    | StdDev   | Gen0     | Allocated …
```
> Add nkey and sha512 micro benchmarks and sanity check tests

- src/NATS.Client.KeyValueStore/NatsKVStore.cs
Convert.TryFromBase64String output buffer was potentially too small. Fixed to use the base64 string length which would be more than enough to fit decoded data.
> Fixed base64 decode buffer size

- src/NATS.Client.JetStream/INatsJSConsumer.cs
- src/NATS.Client.JetStream/NatsJSOrderedConsumer.cs
- tests/NATS.Client.JetStream.Tests/OrderedConsumerTest.cs
With this PR we formalize the use of Fetch no_wait since even though usage is discouraged there are valid scenarios we need to use fetch with no_wait e.g.:
* Empty streams or where we just want to get a snapshot of messages
* IoT applications where fetch is performed at a very low frequency
> Use fetch no wait for empty streams

- src/NATS.Client.Core/Internal/SslStreamConnection.cs
- src/NATS.Client.Core/Internal/TcpConnection.cs
- src/NATS.Client.Core/Internal/WebSocketConnection.cs
- tests/NATS.Client.TestUtilities/MockServer.cs
When watching wireshark, I noticed a lot of `RST` instead of graceful `FIN`
So looking into it more
- TCP Socket - calling `_socket.Shutdown(SocketShutdown.Both);` seems to resolve the RST
- SSL - I guess we forgot to Dispose the SSLStream?  oops.  adding the Dispose still results in a RST on Linux in some cases though, but I'm not sure there is much we can do about it
- WebSocket - needed to call `CloseAsync` which looks like it actually does send another application-level packet, so I included a timeout on that.  But I am guessing if the socket is already disconnected that will return immediately with an exception
> Gracefully close sockets

- src/NATS.Client.KeyValueStore/NatsKVContext.cs
When setting a MaxAge less than the default DuplicateWindow value, you receive the following error. This PR fixes this.
```
NATS.Client.JetStream.NatsJSApiException: duplicates window can not be larger then max age
at NATS.Client.JetStream.Internal.NatsJSResponse`1.EnsureSuccess() in C:\SourceControl\Random\nats.net.v2\src\NATS.Client.JetStream\Internal\NatsJSResponse.cs:line 27
at NATS.Client.JetStream.NatsJSContext.JSRequestResponseAsync[TRequest,TResponse](String subject, TRequest request, CancellationToken cancellationToken) in C:\SourceControl\Random\nats.net.v2\src\NATS.Client.JetStream\NatsJSContext.cs:line 185
at NATS.Client.JetStream.NatsJSContext.CreateStreamAsync(StreamConfig config, CancellationToken cancellationToken) in …
```
> Prevent KeyValueStore error when MaxAge is set below the default DuplicateWindow value

- src/NATS.Client.JetStream/NatsJSOrderedConsumer.cs
When initial request delivery policy is by time
all subsequent request should still start by
sequence and reset start-time field to avoid
errors returned by server.
> Ordered consumer start time fix

- src/NATS.Client.JetStream/INatsJSContext.cs
- src/NATS.Client.JetStream/Internal/NatsJSJsonSerializer.cs
- src/NATS.Client.JetStream/Models/ConsumerConfig.cs
- src/NATS.Client.JetStream/Models/ConsumerInfo.cs
- src/NATS.Client.JetStream/Models/ConsumerPauseRequest.cs
- src/NATS.Client.JetStream/Models/ConsumerPauseResponse.cs
- src/NATS.Client.JetStream/NatsJSContext.Consumers.cs
- tests/NATS.Client.JetStream.Tests/ConsumerSetupTest.cs
- tests/NATS.Client.JetStream.Tests/ManageConsumerTest.cs
- tests/NATS.Client.JetStream.Tests/TimeSpanJsonTests.cs
- tests/NATS.Client.KeyValueStore.Tests/NatsKVContextFactoryTest.cs
- tests/NATS.Client.ObjectStore.Tests/NatsObjContextFactoryTest.cs
Resolves https://github.com/nats-io/nats.net.v2/issues/416
Adds support for pausing and resuming consumers.
- The `NatsJSContext.Consumers` now has methods to `PauseConsumerAsync(stream, consumer, pauseUntil)`, as well as `ResumeConsumerAsync(stream, consumer)`.
- `ConsumerConfiguration` now has support for setting `PauseUntil` as well. Allowing to set it during consumer creation.
The implementation is similar to and based on the changes I made for the Java client: https://github.com/nats-io/nats.java/pull/1093
Am not too familiar with .NET, and this is the first time contributing to this client. Please let me know if I'm missing any things specific to .NET or this client, that can be improved further.
> Implement Consumers Pause

- sandbox/MinimumWebApp/MinimumWebApp.csproj
- sandbox/MinimumWebApp/Program.cs
- src/NATS.Extensions.Microsoft.DependencyInjection/NatsBuilder.cs
- tests/NATS.Extensions.Microsoft.DependencyInjection.Tests/NatsHostingExtensionsTests.cs
When swapping my code over to use the new hosting extensions I found what appears to be blunder of mine on the visibility of the `Build()` method. In order to prevent confusion for consumers thinking they need to call this method, I think hiding it would be best.
```cs
services.AddNatsClient(
nats =>
{
nats.ConfigureOptions(ops => ops with { Url = config.Url });
nats.Build(); // oops, this could cause confusion
});
```
> Make Build() on NatsBuilder Internal

- src/NATS.Client.Core/Internal/NuidWriter.cs
- tests/NATS.Client.Core.Tests/NuidWriterTests.cs
- tests/NATS.Client.Services.Tests/ServicesTests.cs
Fixed nuid sequence so the last few digits change similar to Go reference implementation.
there is also a report that Service ids aren't being generated uniquely which relies on NUIDs. I was not able to reproduce this but reminded me an old test fix I made (` DifferentThreads_DifferentPrefixes()` which is now reverted) which was failing intermittently due to id clashes.
cc @jasper-d
> Fix NUID sequence

- sandbox/Example.JetStream.PullConsumer/Program.cs
- src/NATS.Client.JetStream/Models/ConsumerConfig.cs
- src/NATS.Client.JetStream/Models/ConsumerConfigAckPolicy.cs
- tests/NATS.Client.CheckNativeAot/Program.cs
- tests/NATS.Client.Core.MemoryTests/NatsConsumeTests.cs
- tests/NATS.Client.JetStream.Tests/JetStreamTest.cs
- tests/NATS.Client.JetStream.Tests/ManageConsumerTest.cs
- tests/NATS.Client.JetStream.Tests/ParseJsonTests.cs
- tests/NATS.Net.DocsExamples/JetStream/ManagingPage.cs
Currently the no-args constructor for `ConsumerConfig` does not set the `AckPolicy` for the consumer, which defaults it to `None`. This is confusing given that the NATS docs state that the default `AckPolicy` is `Explicit`:
https://docs.nats.io/nats-concepts/jetstream/consumers#ackpolicy
This has led to unexpected behaviors since we had expected this to be set to `Explicit` by default for all consumers.
This PR changes the no-args `ConsumerConfig` constructor to set the `AckPolicy` to `Explicit`, to be the same as the constructor with a durable name.
> Change ConsumerConfig AckPolicy default to Explicit

- src/NATS.Client.Core/INatsConnection.cs
- src/NATS.Client.Core/NatsConnection.RequestReply.cs
- tests/NATS.Client.Core.Tests/RequestReplyTest.cs
- tests/NATS.Client.JetStream.Tests/NatsJsContextFactoryTest.cs
Proposing a convenience method where request payload isn't required in request-reply calls. It is fairly common to request data without sending any payload. With this method application code can avoid boilerplate null data parameter and request type parameter making the call much more succinct.
```csharp
// current way of sending an empty request payload
var reply1 = await nats.RequestAsync<object, int>(subject, data: null);
// proposed API. calls the method above
var reply2 = await nats.RequestAsync<int>(subject);
```
> [PROPOSAL] Add overload for empty requests

- sandbox/MicroBenchmark/PublishParallelBench.cs
- sandbox/MicroBenchmark/PublishSerialBench.cs
- sandbox/MicroBenchmark/Subscribe.cs
- src/NATS.Client.Core/Internal/ActivityEndingMsgReader.cs
- src/NATS.Client.Core/NatsConnection.Subscribe.cs
- src/NATS.Client.Core/NatsSub.cs
- tests/NATS.Client.Core.MemoryTests/NatsSubTests.cs
Resolves #499 
Resolves #505 
Adds GC keepalive calls to `ActivityEndingMsgReader` in order to prevent sub from being GC'd while the channel reader is being interacted with.
Learned about `GCHandle.Alloc` from this blog post - [Using GC.KeepAlive in async methods](https://minidump.net/c-using-gc-keepalive-in-async-methods-8d20fd79f0a0/)
I left `RegisterSubAnchor` in place for now as I saw it was in-use still in the JetStream project.  But if every sub there uses an `ActivityEndingMsgReader` it should be able to be eliminated.
> Keep sub alive when reading channel

- src/NATS.Client.Core/NatsConnection.RequestReply.cs
- src/NATS.Client.Core/NatsConnection.Subscribe.cs
- src/NATS.Client.JetStream/NatsJSConsumer.cs
- src/NATS.Client.JetStream/NatsJSContext.cs
- src/NATS.Client.JetStream/NatsJSOrderedConsumer.cs
- src/NATS.Client.KeyValueStore/NatsKVStore.cs
Follow-up to #506
- Prefer using sub channel ReadAllAsync where it was easy to swap out based on benchmark: https://github.com/nats-io/nats.net.v2/pull/506#issuecomment-2148235951
- Remove remaining SubAnchor references since `ActivityEndingMsgReader` should now be keeping those subs alive
> Prefer sub channel ReadAllAsync and remove SubAnchor

- src/NATS.Client.KeyValueStore/INatsKVStore.cs
- src/NATS.Client.KeyValueStore/Internal/NatsKVWatcher.cs
- src/NATS.Client.KeyValueStore/NatsKVOpts.cs
- src/NATS.Client.KeyValueStore/NatsKVStore.cs
- tests/NATS.Client.KeyValueStore.Tests/NatsKVWatcherTest.cs
> Add ResumeAtRevision support to KV Watcher

- sandbox/MicroBenchmark/JSPublishBench.cs
- sandbox/MicroBenchmark/MicroBenchmark.csproj
- src/NATS.Client.JetStream/INatsJSContext.cs
- src/NATS.Client.JetStream/Internal/NatsJSErrorAwareJsonSerializer.cs
- src/NATS.Client.JetStream/NatsJSContext.cs
- src/NATS.Client.JetStream/NatsJSJsonSerializer.cs
- src/NATS.Client.JetStream/NatsJSPublishConcurrentFuture.cs
- tests/NATS.Client.JetStream.Tests/PublishConcurrentTests.cs
- tests/NATS.Client.KeyValueStore.Tests/NatsKVContextFactoryTest.cs
- tests/NATS.Client.ObjectStore.Tests/NatsObjContextFactoryTest.cs
- tests/NATS.Client.Platform.Windows.Tests/BasicTests.cs
- tests/NATS.Client.Platform.Windows.Tests/TlsTests.cs
(apologies for attaching too many reviewers. please review if you have the time)
| Method                   | Batch | Mean         | Error         | StdDev      | Gen0     | Gen1     | Gen2    | Allocated  |
|------------------------- |------ |-------------:|--------------:|------------:|---------:|---------:|--------:|-----------:|
| PublishAsync             | 1     |     151.0 us |      34.13 us |     1.87 us |   0.2441 |        - |       - |    3.81 KB |
| PublishConcurrentlyAsync | 1     |     150.7 us |      57.45 us |     3.15 us |   0.2441 |        - |       - |    3.79 KB |
| PublishAsync             | 10    |   1,319.3 us |     149.59 us |     8.20 us |   1.9531 |        - |       - |   36.43 KB |
| PublishConcurrentlyAsync | 10    |     249.9 us |      29.56 us |     1.62 us | …
> JetStream Concurrent Publish

- src/NATS.Client.KeyValueStore/INatsKVContext.cs
- src/NATS.Client.KeyValueStore/NatsKVContext.cs
- tests/NATS.Client.KeyValueStore.Tests/KeyValueContextTest.cs
> Full coverage kv management methods

- src/NATS.Client.Core/Internal/NuidWriter.cs
Previous commit about this issue reverted since it wasn't fixing the issue. The actual error was:
```
Error: IL2CPP error for method 'System.Char[] NATS.Client.Core.Internal.NuidWriter::Refresh(System.UInt64&)' in assembly NATS.Client.Core.dll
System.ArgumentOutOfRangeException:
Cannot create a constant value for types of System.UIntPtr for System.UIntPtr NATS.Client.Core.Internal.NuidWriter::NuidLength (Parameter 'declaredParameterOrFieldType')
```
With this fix now it compiles fine:
Looking at Unsafe.Add examples passing in uint or int instead of nuint is fine:
e.g. https://github.com/dotnet/runtime/blob/a7efcd9ca9255dc9faa8b4a2761cdfdb62619610/src/libraries/System.Private.CoreLib/src/System/Buffer.cs#L84
Note: I had to revert the last two commits (so ignore the previous four commits) …
> Fix il2cpp error (take 2)

- README.md
- REPO_RENAME.md
Added an announcement about the upcoming rename of the current repository to `nats.net`. This change is reflected in a new file REPO_RENAME.md, detailing the rationale behind the renaming and its impact on developers. Also updated the README.md file to include a warning about the impending rename and a link to the announcement.
> Add repository rename announcement

- sandbox/MicroBenchmark/NewInboxBenchmarks.cs
- src/NATS.Client.Core/Internal/NuidWriter.cs
- src/NATS.Client.Core/NatsConnection.RequestReply.cs
- tests/NATS.Client.Core.Tests/NatsConnectionTest.cs
- tests/NATS.Client.Core.Tests/NuidWriterTests.cs
Use a more idiomatic implementation for `NewInbox` and improve performance.
| Method               | Rev | Runtime       | Mean     | Error    | StdDev   | Gen0   | Allocated |
|--------------------- |---- |-------------- |---------:|---------:|---------:|-------:|----------:|
| TryWriteNuid         |Base | .NET 8.0      | 31.92 ns | 0.672 ns | 0.800 ns |      - |         - |
| TryWriteNuid         |PR   | .NET 8.0      | 30.66 ns | 0.650 ns | 1.171 ns |      - |         - |
| NewInbox_ShortPrefix |Base | .NET 8.0      | 59.64 ns | 1.258 ns | 1.921 ns | 0.0612 |     128 B |
| NewInbox_ShortPrefix |PR   | .NET 8.0      | 46.89 ns | 0.945 ns | 1.865 ns | 0.0612 |     128 B |
| NewInbox_LongPrefix  |Base | .NET 8.0      | 79.69 ns | 1.674 ns | 4.230 ns | 0.1988 |     416 B |
| …
> Use string.Create when building a new inbox string

- src/NATS.Client.Core/NATS.Client.Core.csproj
- src/NATS.Client.JetStream/Models/StoredMessage.cs
- src/NATS.Client.JetStream/NATS.Client.JetStream.csproj
- src/NATS.Client.KeyValueStore/NatsKVStore.cs
- src/NATS.Client.ObjectStore/Internal/Encoder.cs
- src/NATS.Client.ObjectStore/NatsObjStore.cs
Resolves #518 
tl;dr - we are optimizing a lot of our base64 encode parsing by using `System.Text.Buffers` as it has NetStandard2.0 compatibility, which will also allow us to have less code to maintain long term. :)
This is a semi-breaking change however, as it does the following:
1. `System.Text.Json` is updated to the newest version, to support `ReadOnlyMemory<byte>`
1. this version is compatible with NetStandard2.0 and Net6, so, win-win?
2. Other win-win, by doing this, we instead rely on the implementations of how `System.Text.Json` handles `ReadOnlyMemory<byte>`, i.e. it does the Base64 decoding internally and should be 'good' for all versions (if there is issue we can always PR them!)
2. We use `ReadOnlyMemory<Byte>` for our model here now. If someone is somehow relying on that type …
> Base64 Encoding simplification + optimization

- README.md
- REPO_RENAME.md
The renaming info of the repository has been updated from the future tense to the past tense in both README.md and REPO_RENAME.md files. An additional link has been added in README.md pointing to the old NATS .NET v1 repository.
> Update repository renaming information

- src/NATS.Client.Core/Internal/SubscriptionManager.cs
- src/NATS.Client.Services/Internal/SvcListener.cs
- src/NATS.Client.Services/NatsSvcEndPoint.cs
- src/NATS.Client.Services/NatsSvcLogEvents.cs
- src/NATS.Client.Services/NatsSvcServer.cs
- tests/NATS.Client.Services.Tests/ServicesSerializationTest.cs
The commit refactors the error handling and logging within the NatsSvcServer and NatsSvcEndPoint classes. Updates have been made to the SvcListener, enhancing message logging and ensuring clean unsubscription on object disposal. The changes also facilitate better debugging and analysis by adding more logging statements for subscription handling within the SubscriptionManager class. Additional updates are made to handle possible errors in the handler loop within the NatsSvcEndPoint class.
> Add logging enhancements and improve error handling

- src/NATS.Client.JetStream/Internal/NatsJSFetch.cs
- src/NATS.Client.JetStream/Internal/NatsJSOptsDefaults.cs
Allow heartbeat timeout to be set as TimeSpan.Zero so it's not sent to server e.g.
```
PUB $JS.API.CONSUMER.MSG.NEXT.s1.c1 _INBOX.hHyTxVZaGlxkX2lhPMFlho 35
{"expires":30000000000,"batch":100}
```
> Fetch idle timeout default fix

- tests/NATS.Client.JetStream.Tests/MetadataParserTests.cs
Introduced `MetadataParserTests` to validate parsing logic for various `Subject` formats.
We also verified if extra tokens were to be passed in we'd ignore them.
> Add unit tests for MetadataParser

- src/NATS.Client.Core/Internal/WebSocketConnection.cs
- src/NATS.Client.Core/NatsConnection.cs
- src/NATS.Client.Core/NatsOpts.cs
- tests/NATS.Client.Core.Tests/WebSocketOptionsTest.cs
- tests/NATS.Client.TestUtilities/InMemoryTestLoggerFactory.cs
- tests/NATS.Client.TestUtilities/NATS.Client.TestUtilities.csproj
- tests/NATS.Client.TestUtilities/OutputHelperLogger.cs
- tests/NATS.Client.TestUtilities/WebSocketMockServer.cs
As discussed in #305 this PR is adding support for manipulating the ClientWebSocketOptions used for WebSocket connections. Among other things, this allows setting an authorization header.
* resolves #305
> NatsOpts.ConfigureWebSocketOpts callback handler

- .github/workflows/perf.yml
- .github/workflows/test.yml
- sandbox/MicroBenchmark/NewInboxBenchmarks.cs
- src/NATS.Client.Core/NatsConnection.RequestReply.cs
- src/NATS.Client.Core/Nuid.cs
- src/NATS.Client.Core/NuidWriter.cs
- src/NATS.Client.JetStream/Internal/NatsJSOrderedPushConsumer.cs
- src/NATS.Client.JetStream/NatsJSContext.Consumers.cs
- src/NATS.Client.KeyValueStore/Internal/NatsKVWatcher.cs
- src/NATS.Client.ObjectStore/NatsObjStore.cs
- src/NATS.Client.Services/NatsSvcServer.cs
- tests/NATS.Client.Core.Tests/NuidTests.cs
- tests/NATS.Client.KeyValueStore.Tests/KeyValueStoreTest.cs
This PR makes the `NuidWriter` class public, and moves it into the `Core` namespace out of the `Internal` namespace. 
Resolves #617.
> Make NuidWriter public

- .github/workflows/perf.yml
- .github/workflows/test.yml
- src/NATS.Client.Core/Commands/ProtocolWriter.cs
- src/NATS.Client.Core/Internal/SslClientAuthenticationOptionsExtensions.cs
- src/NATS.Client.Core/Internal/SslStreamConnection.cs
- src/NATS.Client.Core/NKeyPair.cs
- src/NATS.Client.Core/NatsConnection.cs
- src/NATS.Client.Core/NatsSubBase.cs
- src/NATS.Client.JetStream/Internal/NatsJSNotificationChannel.cs
- src/NATS.Client.JetStream/Internal/NatsJSOrderedPushConsumer.cs
- src/NATS.Client.KeyValueStore/Internal/NatsKVWatcher.cs
- src/NATS.Client.ObjectStore/NatsObjStore.cs
This PR fixes various disposable issues
> Fix various disposable issues

- .github/workflows/perf.yml
- .github/workflows/test.yml
- src/NATS.Extensions.Microsoft.DependencyInjection/NatsBuilder.cs
- tests/NATS.Extensions.Microsoft.DependencyInjection.Tests/MyResolvedService.cs
- tests/NATS.Extensions.Microsoft.DependencyInjection.Tests/NatsHostingExtensionsTests.cs
The NATS Client DependencyInjection package (`NatsBuilder`) does all configuration inline when the `.AddNatsClient` method is called. This does not allow consumers to build up a NATS instance across multiple packages, and all configuration must be defined at registration time, rather than runtime.
`MyCompany.Nats.Core`:
```cs
public static IServiceCollection AddMyCompanyNats(this IServiceCollection services)
{
services.AddNatsClient(natsBuilder => natsBuilder
.PoolSize(3)
.ConfigureOptions(opts => {
return opts; // How to configure??
}))
return services;
}
```
Add `IServiceProvider` overloads to configuration methods, to enable resolution-time configuration:
`MyCompany.Nats.Core`:
```cs
interface IConfigurator
{
NatsOpts Configure(NatsOpts opts);
}
public static IServiceCollection …
```
> ServiceProvider callback for NATS DI configuration;

- src/NATS.Client.JetStream/Internal/NatsJSConsume.cs
- src/NATS.Client.JetStream/NatsJSConsumer.cs
- tests/NATS.Client.JetStream.Tests/ConsumerConsumeTest.cs
Implemented a new method `Delivered` to accurately adjust the pending message size on message delivery. Ensured pending checks and size adjustments are correctly handled during reconnect and message delivery to maintain a consistent consumer state. Also updated tests to validate these changes.
resolves #608
> Fixed consume pending message calculation

- src/NATS.Client.Core/Internal/netstandard.cs
Adds missing type forwarders to fix `MissingMethodExceptions` when this library is consumed by a .NET standard library, which is then consumed by a > .NET 5 app
Resolves #640
> Adds type-forwarders NET 5.0+

- src/NATS.Client.JetStream/Models/StreamSource.cs
- src/NATS.Client.JetStream/NatsJSJsonSerializer.cs
- tests/NATS.Client.JetStream.Tests/TimeSpanJsonTests.cs
> Add DateTimeOffset converter to handle UTC serialization

- src/NATS.Client.Core/Internal/NatsUri.cs
- src/NATS.Client.Core/NatsConnection.cs
- src/NATS.Client.Core/NatsOpts.cs
- src/NATS.Client.Simplified/NatsClient.cs
- tests/NATS.Client.Core.Tests/ClusterTests.cs
- tests/NATS.Client.Core.Tests/NatsConnectionTest.Auth.cs
- tests/NATS.Client.CoreUnit.Tests/OptsUrlTests.cs
- tests/NATS.Client.TestUtilities/NatsServer.cs
- tests/NATS.Client.TestUtilities/NatsServerOpts.cs
@mtmk As discussed, here is the PR for support for Auth in URL, I also made it to support token in URL, since if it works with username + password, I think users would also expect for it to work with a token.
Aspire PR that will uses this: https://github.com/dotnet/aspire/pull/6259
Note: some Serializer unit test were already failing before I made changes.
> Add support for auth in URL

- src/NATS.Client.Core/INatsSerialize.cs
- tests/NATS.Client.Core2.Tests/SerializerTest.cs
Doesn't make sense to serialize datetime types with the default culture dependent formatting since it might differ between different platforms. with this PR we use ISO8601 formatting as indicated by `O` to maximize the compatibility among different platforms and languages.
> Fix date time serialization to use ISO8601

- .github/ISSUE_TEMPLATE/config.yml
- CONTRIBUTING.md
- README.md
- docs/documentation/advanced/security.md
- docs/toc.yml
> Fix documentation links

- .github/workflows/test.yml
- src/NATS.Client.Core/HeaderWriter.cs
- src/NATS.Client.Core/Internal/HeaderWriter.cs
- src/NATS.Client.Core/NatsHeaders.cs
- tests/NATS.Client.CoreUnit.Tests/NatsHeaderTest.cs
Open Header.Writer class and create GetBytesLength method for calculating NatsHeaders size (length in bytes) up front to call Publish for large Nats message which may exceeds payload size against server's maximum payload size.
* fixes #638
> open Header.Writer class and create GetBytesLength method

- .gitignore
- src/NATS.Client.ObjectStore/NatsObjStore.cs
- tests/NATS.Client.ObjectStore.Tests/ObjectStoreTest.cs
> Fixed an exception which happens when PutAsync is used more than once and activity logging is enabled in main project

- src/NATS.Client.Core/Internal/HeaderWriter.cs
- src/NATS.Client.Core/NatsException.cs
I think we did put private throw helpers in a few classes going forward static method on the exception class itself looks very expressive and accessible.
> @to11mtm 
> Main advantage of such is we can get some better inlining/opts and avoid certain callstack checks on happy path....
see also review comments https://github.com/nats-io/nats.net/pull/674#discussion_r1839088340
> Refactor exception handling in NatsException

- src/NATS.Client.Core/INatsConnection.cs
- src/NATS.Client.Core/ISocketConnection.cs
- src/NATS.Client.Core/Internal/ISocketConnection.cs
- src/NATS.Client.Core/NatsConnection.cs
- tests/NATS.Client.Core.Tests/NatsConnectionTest.cs
- tests/NATS.Client.JetStream.Tests/NatsJsContextFactoryTest.cs
This change adds the `OnSocketAvailableAsync` hook, allowing users to perform actions on the socket once it becomes available. This is particularly useful for scenarios where an HTTP proxy is required to connect to a NATS server.
This hook enables users to interact with the socket directly, allowing custom actions such as sending an HTTP CONNECT request to establish a tunnel through a proxy.
```csharp
_connection.OnSocketAvailableAsync = async (_socket) =>
{
var hostname = "my-http-proxy-host";
var port = 3128;
string connectRequest = $"CONNECT {hostname}:{port} HTTP/1.1\r\nHost: {hostname}:{port}\r\n\r\n";
byte[] requestBytes = Encoding.ASCII.GetBytes(connectRequest);
await _socket.SendAsync(requestBytes);
// Validate proxy response
byte[] buffer = new byte[4096];
int bytesRead = await …
```
> Add OnSocketAvailableAsync Hook

- src/NATS.Client.Core/INatsClient.cs
- src/NATS.Client.Core/NatsConnection.Reconnect.cs
- src/NATS.Client.Simplified/NatsClient.cs
- tests/NATS.Client.Core.Tests/NatsConnectionTest.cs
- tests/NATS.Client.JetStream.Tests/NatsJsContextFactoryTest.cs
Resolves #479
- Add `ReconnectAsync` method
- Add test for `ReconnectAsync` method
I decided to follow naming proposed in [design issue](https://github.com/nats-io/nats-architecture-and-design/issues/259).
Ps. `OnSocketAvailableAsync_ShouldBeInvokedOnReconnection()` test in `NatsConnectionTest.cs` sometimes passes sometimes fails, so maybe there is some race? I've also noticed that it uses default `TransportType` (Tcp) instead of one provided by `NatsConnectionTest` class. It means same test runs 4 times if i understand correctly.
>  Add (force) reconnect method 

- .github/workflows/test.yml
.NET 6 was missing so it didn't run those tests and failed the CI builds.
> Make sure we also install .net 6 for the tests

- src/NATS.Client.Core/INatsConnection.cs
- src/NATS.Client.Core/NatsConnection.cs
- src/NATS.Client.Core/NatsEventArgs.cs
- tests/NATS.Client.Core.Tests/NatsConnectionTest.cs
- tests/NATS.Client.JetStream.Tests/NatsJsContextFactoryTest.cs
- tests/NATS.Client.TestUtilities/NatsServer.cs
Resolves #23 
I had two ideas for approaching this issue:
- Make `WritableServerInfo` property and add setter, that will check if LDM has changed to `true`
- Add a trigger method that writes the event to a channel in `NatsConnection` and invoke it directly from `NatsReadProtocolProcessor` after recieving INFO from server with LDM.
I decided to go with first option.
There is one thing i am not sure of: should anything be passed as argument to the `LameDuckModeActivated` event? Currently, it is an empty string.
> Implement Lame Duck Mode Event Handler

- tests/NATS.Client.Core.Tests/ClusterTests.cs
- tests/NATS.Client.Core.Tests/TlsClientTest.cs
- tests/NATS.Client.JetStream.Tests/ClusterTests.cs
- tests/NATS.Client.JetStream.Tests/ConsumerConsumeTest.cs
- tests/NATS.Client.JetStream.Tests/CustomSerializerTest.cs
- tests/NATS.Client.JetStream.Tests/DoubleAckNakDelayTests.cs
- tests/NATS.Client.JetStream.Tests/ErrorHandlerTest.cs
- tests/NATS.Client.JetStream.Tests/ManageConsumerTest.cs
- tests/NATS.Client.JetStream.Tests/OrderedConsumerTest.cs
- tests/NATS.Client.JetStream.Tests/PublishTest.cs
- tests/NATS.Client.JetStream.Tests/Utils.cs
- tests/NATS.Client.TestUtilities/NatsProxy.cs
- tests/NATS.Client.TestUtilities/NatsServer.cs
- tests/NATS.Client.TestUtilities/Utils.cs
* Added pre connect retry loop for clients to be ready
* moved a few test to use a single nats-server rather than spawning a new one in each test (look for `[Collection("nats-server")]` on test classes)
* fixed test proxy sync issues
* extended timeouts to 30s (this one probably not that helpful but my assumption is if they are running on really small VMs with a single CPU than the extra wait might help)
> Fix JetStream test flappers

- src/NATS.Client.Core/NatsResult.cs
- src/NATS.Client.JetStream/INatsJSContext.cs
- src/NATS.Client.JetStream/NatsJSContext.cs
- src/NATS.Client.KeyValueStore/INatsKVStore.cs
- src/NATS.Client.KeyValueStore/NatsKVStore.cs
- tests/NATS.Client.JetStream.Tests/PublishTest.cs
- tests/NATS.Client.KeyValueStore.Tests/KeyValueStoreTest.cs
- tests/NATS.Client.KeyValueStore.Tests/NatsKVContextFactoryTest.cs
- tests/NATS.Client.ObjectStore.Tests/NatsObjContextFactoryTest.cs
Added the following commands to KVStore ;
- TryCreateAsync
- TryUpdateAsync
- TryDeleteAsync
- TryPurgeAsync
* resolves #441
> Added Additional Try Commands to KVStore

- NATS.Net.sln
- src/NATS.Client.JetStream/Models/StreamConfig.cs
- src/NATS.Client.KeyValueStore/INatsKVStore.cs
- src/NATS.Client.KeyValueStore/NatsKVConfig.cs
- src/NATS.Client.KeyValueStore/NatsKVContext.cs
- src/NATS.Client.KeyValueStore/NatsKVStore.cs
- tests/NATS.Client.KeyValueStore.Tests/KeyValueStoreTest.cs
> [!NOTE]
> * to be merged into #733 
* Adds support to set the `AllowMsgTTL` flag for KV streams
* Adds a `Timestamp ttl` optional parameter to the `PutAsync<T>` method on `INatsKVStore`
* Note that this does break API backwards compatibility if users are using their own serializers, but that's seems to be how it's done in Go client, so it's up to you if you want to create a separate overload for each method that can accept a TTL value
* Added a single test to test the TTL functionality. This currently requires the tests to have access to the latest nightly binary
TODO:
* More exhaustive tests
* Add support to the `CreateAsync/UpdateAsync` API methods
see also [ADR-43](https://github.com/nats-io/nats-architecture-and-design/blob/main/adr/ADR-43.md)
> Initial implementation of per-key-TTL for KV

- src/NATS.Client.Core/NatsConnection.cs
Keep a reference to long-running task to avoid potential GC.
> Fix task tracking

- src/NATS.Client.JetStream/Models/StreamConfig.cs
Simple change to make the StreamConfig class available for external (de)serialization, e.g. for advisory messages such as  StreamSnapshotResponse.
> Make the parameter-less StreamConfig constructor public

- src/NATS.Client.KeyValueStore/NatsKVContext.cs
- src/NATS.Client.KeyValueStore/NatsKVStore.cs
- tests/NATS.Client.KeyValueStore.Tests/DirectGetTest.cs
Proposed solution for #770 
* fixes #770
> Add support for Direct Get API with key in subject

- src/NATS.Client.KeyValueStore/Internal/NatsKVWatcher.cs
- tests/NATS.Client.KeyValueStore.Tests/NatsKVWatcherTest.cs
> Fix handling for OnNoData when ignoring deletes

- README.md
We've stopped testing with .NET 6.0:
* This is to reduce the burden on CI (both running and maintenance)
* [.NET 6 reached End of Support on November 2024](https://devblogs.microsoft.com/dotnet/dotnet-6-end-of-support/)
* See also Microsoft's [.NET Support Policy](https://dotnet.microsoft.com/en-us/platform/support/policy))
* It's relatively easy for applications to update to later versions
* We are still targeting .NET 6 not to disturb any applications but thinking about eventually dropping .NET 6 support completely to reduce maintenance cost.
[no ci]
> Stopped testing with net6.0

- tests/NATS.Net.DocsExamples/.editorconfig
- tests/NATS.Net.DocsExamples/Advanced/IntroPage.cs
- tests/NATS.Net.DocsExamples/Advanced/SecurityPage.cs
- tests/NATS.Net.DocsExamples/Advanced/SerializationPage.cs
- tests/NATS.Net.DocsExamples/Core/IntroPage.cs
- tests/NATS.Net.DocsExamples/Core/PubSubPage.cs
- tests/NATS.Net.DocsExamples/Core/QueuePage.cs
- tests/NATS.Net.DocsExamples/Core/ReqRepPage.cs
- tests/NATS.Net.DocsExamples/IndexPagePub.cs
- tests/NATS.Net.DocsExamples/IndexPageSub.cs
- tests/NATS.Net.DocsExamples/IntroPage.cs
- tests/NATS.Net.DocsExamples/JetStream/ConsumePage.cs
- tests/NATS.Net.DocsExamples/JetStream/IntroPage.cs
- tests/NATS.Net.DocsExamples/JetStream/ManagingPage.cs
- tests/NATS.Net.DocsExamples/JetStream/PublishPage.cs
- tests/NATS.Net.DocsExamples/KeyValueStore/IntroPage.cs
- tests/NATS.Net.DocsExamples/ObjectStore/IntroPage.cs
- tests/NATS.Net.DocsExamples/Services/IntroPage.cs
Use explicit types for docs for clarity.
> Docs examples update

- src/NATS.Client.Core/NatsConnection.cs
- src/NATS.Client.Core/NatsOpts.cs
- src/NATS.Client.Core/NatsUri.cs
* fixes #802 
* retry for (#804)
> Fix proxy with TLS scenario with SocketConnectionFactory

- src/NATS.Client.JetStream/Models/ConsumerConfig.cs
- src/NATS.Client.JetStream/NatsJSJsonSerializer.cs
- tests/NATS.Client.JetStream.Tests/TimeSpanJsonTests.cs
Proposed enhancement for #422.
This change introduces a breaking change that all existing definition is required to be replaced with TimeSpan type.
> Use TimeSpan for backoff consumer config

- src/NATS.Client.Core/NatsSubBase.cs
- src/NATS.Client.JetStream/Internal/NatsJSConsume.cs
- src/NATS.Client.JetStream/Internal/NatsJSFetch.cs
- src/NATS.Client.JetStream/Internal/NatsJSOrderedConsume.cs
There are cases where exception is thrown when disposing the base subscription which leaves timers undisposed in which case they go on firing even though the subscription object is long gone.
> Fix subscriptions dispose exception handling

- src/NATS.Client.Core/Internal/Telemetry.cs
> #863 Fix naming of consumer group attribute

- src/NATS.Client.JetStream/NatsJSMsg.cs
> Obsolete ReplyAsync method for NatsJsMsg

- src/NATS.Client.KeyValueStore/INatsKVStore.cs
- src/NATS.Client.KeyValueStore/NatsKVStore.cs
Expose the ttl-versions of update
> Add TTL versions of UpdateAsync/TryUpdateAsync to INatsKvStore

- src/NATS.Client.Core/Internal/SubscriptionManager.cs
- src/NATS.Client.Core/Internal/Telemetry.cs
- src/NATS.Client.Core/NatsInstrumentationContext.cs
- src/NATS.Client.Core/NatsInstrumentationOptions.cs
- src/NATS.Client.Core/NatsMsgTelemetryExtensions.cs
- src/NATS.Client.JetStream/NatsJSTelemetryExtensions.cs
`public static NatsInstrumentationOptions Default => new();` meant that any time `NatsInstrumentationOptions.Default` was accessed it would return a new instance and essentially all settings would get reset, defeating the whole purpose. It's weird this wasn't caught in #859! 😅
Also, made `GetActivityContext` an extension on `NatsHeaders` so that it can also be used in the context of `NatsJSMsg`s and even when you only have a `NatsHeaders` instance in scope.
Found out also that `NatsInstrumentationContext.ActivityContext` didn't need to be made nullabe; in fact, that would've been things confusing.
> fix: `NatsInstrumentationOptions.Default` gets reset each time

- .github/workflows/signoffs.yml
- src/NATS.Client.JetStream/NatsJSContext.cs
- src/NATS.Client.JetStream/NatsJSOpts.cs
The previous implementation used the defaults from the connections NatsOpts RequestTimeout for JetStream specific request/reply operations.
This change allows setting a separate default value for JetStream operations from the core NatsOpts default.
> Add RequestTimeout option to NatsJSOpts for request operations

- src/NATS.Client.Core/Commands/CommandWriter.cs
Previously applied fix (#926) was not allowing reader buffers to be flushed. with this fix we are letting buffers to be flushed (after the `_pipeWriter.CompleteAsync()` call) before we cancel the loop completely.
cc @aDisplayName
> Fix CommandWrite dispose fix

- .github/workflows/perf.yml
- .github/workflows/test_linux.yml
- .github/workflows/test_linux_core.yml
- .github/workflows/test_windows.yml
This pull request updates the CI workflow configuration by removing the NATS Server v2.9.x from the test and performance job matrices. This streamlines the workflows to only run against supported or current server versions.
> Remove v2.9 testing from GitHub workflows

- src/NATS.Client.Core/NatsSubBase.cs
We just experienced an issue where our application stopped processing messages because an OutOfMemoryException was thrown and swallowed in ReceiveAsync. Framework docs explicitly state:
> Because [SystemException](https://learn.microsoft.com/en-us/dotnet/api/system.systemexception?view=net-9.0) serves as the base class of a variety of exception types, your code should not throw a [SystemException](https://learn.microsoft.com/en-us/dotnet/api/system.systemexception?view=net-9.0) exception, nor should it attempt to handle a [SystemException](https://learn.microsoft.com/en-us/dotnet/api/system.systemexception?view=net-9.0) exception unless you intend to re-throw the original exception.
> Don't suppress SystemExceptions in NatsSubBase.ReceiveAsync

- src/NATS.Client.ObjectStore/NatsObjStore.cs
ObjectStore.PutAsync was transferring ownership of memory buffer. 
Memory buffer was returned to the pool on serialization. Everything was going smooth until performance degradation. In such case retries were needed using same memory buffer which was already returned to the pool so it might have contain some other data.
This PR keeps ownership for the whole upload process and does not transfer it down to serializer.
You could argue that `using var memoryOwner` may be moved inside `while` loop, but it will just increase pool churn. There are no other `await`s after publishing so this buffer would return to pool for only few CPU cycles.
* fixes #917
> fix: Do not transfer ownership of chunk buffer (issue #917)
